// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void charging1_Animation(lv_obj_t * TargetObject, int delay);
void charging2_Animation(lv_obj_t * TargetObject, int delay);
void charging3_Animation(lv_obj_t * TargetObject, int delay);
void left_on_Animation(lv_obj_t * TargetObject, int delay);
void left_off_Animation(lv_obj_t * TargetObject, int delay);
void bottom_on_Animation(lv_obj_t * TargetObject, int delay);
void bottom_off_Animation(lv_obj_t * TargetObject, int delay);
void phone_Animation(lv_obj_t * TargetObject, int delay);
void big_left_on_Animation(lv_obj_t * TargetObject, int delay);
void ready_on_Animation(lv_obj_t * TargetObject, int delay);
void ready_off_Animation(lv_obj_t * TargetObject, int delay);
void top_on_Animation(lv_obj_t * TargetObject, int delay);
void top_off_Animation(lv_obj_t * TargetObject, int delay);
void end_bar_on_Animation(lv_obj_t * TargetObject, int delay);
void end_bar_off_Animation(lv_obj_t * TargetObject, int delay);
void top_on2_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
lv_obj_t * ui_Home;
lv_obj_t * ui_Full_content_group;
lv_obj_t * ui_Slidebar;
lv_obj_t * ui_Slidebar_bg;
void ui_event_Pricing_group(lv_event_t * e);
lv_obj_t * ui_Pricing_group;
lv_obj_t * ui_Pricing_icon;
lv_obj_t * ui_Pricing_label;
void ui_event_Help_group(lv_event_t * e);
lv_obj_t * ui_Help_group;
lv_obj_t * ui_Help_icon;
lv_obj_t * ui_Help_label;
lv_obj_t * ui_Content_of_objects;
lv_obj_t * ui_Main_bg_img;
lv_obj_t * ui_Statusbar_group;
lv_obj_t * ui_Contact_icon;
lv_obj_t * ui_Call_number;
lv_obj_t * ui_Statusbar_date;
lv_obj_t * ui_Bottom_charger_id;
lv_obj_t * ui_Cardbg_animcontainer;
lv_obj_t * ui_Cardbg;
lv_obj_t * ui_Welcome_title;
lv_obj_t * ui_Charger_extract;
lv_obj_t * ui_Started_h1;
lv_obj_t * ui_carimg;
void ui_event_Start_button_button(lv_event_t * e);
lv_obj_t * ui_Start_button;


// SCREEN: ui_Step1
void ui_Step1_screen_init(void);
void ui_event_Step1(lv_event_t * e);
lv_obj_t * ui_Step1;
lv_obj_t * ui_Full_content2;
lv_obj_t * ui_Slidebar2;
lv_obj_t * ui_Slidebar_bg_;
void ui_event_Pricing_group2(lv_event_t * e);
lv_obj_t * ui_Pricing_group2;
lv_obj_t * ui_Pricing_icon2;
lv_obj_t * ui_Pricing_label2;
void ui_event_Help_group2(lv_event_t * e);
lv_obj_t * ui_Help_group2;
lv_obj_t * ui_Help_icon2;
lv_obj_t * ui_Help_label2;
lv_obj_t * ui_Content_of_objects2;
lv_obj_t * ui_Main_bg_img2;
lv_obj_t * ui_Statusbar_group2;
lv_obj_t * ui_Contact_icon2;
lv_obj_t * ui_Call_number2;
lv_obj_t * ui_Statusbar_date2;
lv_obj_t * ui_Cardbg_animcontainer2;
lv_obj_t * ui_Cardbg2;
lv_obj_t * ui_Step_labels;
lv_obj_t * ui_One_icon;
lv_obj_t * ui_Step;
lv_obj_t * ui_Plugin_h2;
lv_obj_t * ui_First_step;
lv_obj_t * ui_plug;
void ui_event_Next_button_button(lv_event_t * e);
lv_obj_t * ui_Next_button;
lv_obj_t * ui_Plagination;
lv_obj_t * ui_one_gray;
lv_obj_t * ui_two_black;


// SCREEN: ui_Step2
void ui_Step2_screen_init(void);
void ui_event_Step2(lv_event_t * e);
lv_obj_t * ui_Step2;
lv_obj_t * ui_Full_content3;
lv_obj_t * ui_Slidebar3;
lv_obj_t * ui_Slidebar_bg2;
void ui_event_Pricing_group3(lv_event_t * e);
lv_obj_t * ui_Pricing_group3;
lv_obj_t * ui_Pricing_icon3;
lv_obj_t * ui_Pricing_label3;
void ui_event_help_group3(lv_event_t * e);
lv_obj_t * ui_help_group3;
lv_obj_t * ui_Help_icon3;
lv_obj_t * ui_Help_label3;
lv_obj_t * ui_Content_of_objects3;
lv_obj_t * ui_Main_bg_img3;
lv_obj_t * ui_Statusbar_group3;
lv_obj_t * ui_Contact_icon3;
lv_obj_t * ui_Call_number3;
lv_obj_t * ui_Statusbar_date3;
lv_obj_t * ui_Authentication_text;
lv_obj_t * ui_Cardbg_animcontainer3;
lv_obj_t * ui_Cardbg3;
lv_obj_t * ui_Step_labels2;
lv_obj_t * ui_Two_icon;
lv_obj_t * ui_Step3;
lv_obj_t * ui_Authentication_h5;
lv_obj_t * ui_Phone;
lv_obj_t * ui_Plagination2;
lv_obj_t * ui_Two_gray_;
lv_obj_t * ui_Two_black;
lv_obj_t * ui_Qr_container;
lv_obj_t * ui_Qr;
void ui_event_Next_button2_button(lv_event_t * e);
lv_obj_t * ui_Next_button2;


// SCREEN: ui_Connect
void ui_Connect_screen_init(void);
void ui_event_Connect(lv_event_t * e);
lv_obj_t * ui_Connect;
lv_obj_t * ui_Main_bg_img4;
lv_obj_t * ui_Helptext;
lv_obj_t * ui_Cardbg_animcontainer4;
void ui_event_Cardbg4_cardbg(lv_event_t * e);
lv_obj_t * ui_Cardbg4;
lv_obj_t * ui_Connecting_Container;
lv_obj_t * ui_Waiting_title;
lv_obj_t * ui_Connecting_h3;
lv_obj_t * ui_Spinner;


// SCREEN: ui_Welcome
void ui_Welcome_screen_init(void);
void ui_event_Welcome(lv_event_t * e);
lv_obj_t * ui_Welcome;
lv_obj_t * ui_Main_bg_img5;
lv_obj_t * ui_Cardbg_animcontainer5;
lv_obj_t * ui_Cardbg5;
lv_obj_t * ui_Welcome_panel;
lv_obj_t * ui_Welcomimg_title;
lv_obj_t * ui_Welcome_text;
lv_obj_t * ui_Fee_panel;
lv_obj_t * ui_Fee_label;
lv_obj_t * ui_Price_fee;
lv_obj_t * ui_Charging_panel;
lv_obj_t * ui_Charging_text;
lv_obj_t * ui_Amount_text;
lv_obj_t * ui_Charging_speed_panel;
lv_obj_t * ui_Charging_speed;
lv_obj_t * ui_Full_content;
lv_obj_t * ui_Content_of_objects5;
lv_obj_t * ui_Statusbar_date5;
lv_obj_t * ui_Statusbar_group5;
lv_obj_t * ui_Contact_icon5;
lv_obj_t * ui_Call_number5;
lv_obj_t * ui_Ready_img_container;
lv_obj_t * ui_ready;
void ui_event_Continue_button_button(lv_event_t * e);
lv_obj_t * ui_Continue_button;


// SCREEN: ui_Charging
void ui_Charging_screen_init(void);
void ui_event_Charging(lv_event_t * e);
lv_obj_t * ui_Charging;
lv_obj_t * ui_Main_bg_img6;
lv_obj_t * ui_Full_content1;
lv_obj_t * ui_Statusbar_group6;
lv_obj_t * ui_Statusbar_info;
lv_obj_t * ui_Contact_icon6;
lv_obj_t * ui_Call_number6;
lv_obj_t * ui_Statusbar_date6;
lv_obj_t * ui_Space;
lv_obj_t * ui_Cardbg_animcontainer6;
lv_obj_t * ui_Cardbg_container;
lv_obj_t * ui_Charging_time_group;
lv_obj_t * ui_Charging_time;
lv_obj_t * ui_Label_charging;
lv_obj_t * ui_Amount_group;
lv_obj_t * ui_Num_label;
lv_obj_t * ui_Min_label;
lv_obj_t * ui_Charging_cost_group;
lv_obj_t * ui_Charging_cost;
lv_obj_t * ui_Label_cost;
lv_obj_t * ui_Amount_group2;
lv_obj_t * ui_Price_label;
lv_obj_t * ui_Charging_energie_group;
lv_obj_t * ui_Energy_del;
lv_obj_t * ui_Label_energy;
lv_obj_t * ui_Amount_group3;
lv_obj_t * ui_Num_label2;
lv_obj_t * ui_Kwh_label;
lv_obj_t * ui_Main_chargercontainer;
lv_obj_t * ui_State;
lv_obj_t * ui_Full_charger_group;
lv_obj_t * ui_Cardbg6;
lv_obj_t * ui_Anim_bg2;
lv_obj_t * ui_Anim_bg3;
lv_obj_t * ui_Anim_bg1;
lv_obj_t * ui_Mask1;
lv_obj_t * ui_Mask2;
lv_obj_t * ui_Chargebar_fr_cont;
lv_obj_t * ui_Green_startbar;
lv_obj_t * ui_Startbar_indicator;
lv_obj_t * ui_Blue_indicator;
lv_obj_t * ui_Whitespace_2fr;
lv_obj_t * ui_Percent_nums;
lv_obj_t * ui_Percent_num1;
lv_obj_t * ui_Percent_num2;
lv_obj_t * ui_Whitespace1;
lv_obj_t * ui_Cardbg_ghostbtn;
lv_obj_t * ui_Cardbg_animcontainer7;
lv_obj_t * ui_Charging_speed_group;
lv_obj_t * ui_Speed_label;
lv_obj_t * ui_Speed_group;
lv_obj_t * ui_Num_label3;
lv_obj_t * ui_Kw_;
lv_obj_t * ui_Whitespace_ghostbtn;
void ui_event_Stop_button_button(lv_event_t * e);
lv_obj_t * ui_Stop_button;


// SCREEN: ui_End
void ui_End_screen_init(void);
void ui_event_End(lv_event_t * e);
lv_obj_t * ui_End;
lv_obj_t * ui_Main_bg_img7;
lv_obj_t * ui_Full_content4;
lv_obj_t * ui_Statusbar_group7;
lv_obj_t * ui_Statusbar_info6;
lv_obj_t * ui_Contact_icon7;
lv_obj_t * ui_Call_number1;
lv_obj_t * ui_Statusbar_date1;
lv_obj_t * ui_Two_columns;
lv_obj_t * ui_Chart_animcontainer;
lv_obj_t * ui_Full_chart_group;
lv_obj_t * ui_Chart;
lv_obj_t * ui_Total_label;
lv_obj_t * ui_Time_label;
lv_obj_t * ui_Cardbg_and_sum_;
lv_obj_t * ui_Cardbg_animcontainer8;
lv_obj_t * ui_Cardbg7;
lv_obj_t * ui_Fee_group;
lv_obj_t * ui_Total_label2;
lv_obj_t * ui_Num_label4;
lv_obj_t * ui_Fee_group2;
lv_obj_t * ui_Time_label2;
lv_obj_t * ui_Num_label5;
lv_obj_t * ui_Sum_container;
lv_obj_t * ui_Summary_price;
lv_obj_t * ui_Total_cost;
lv_obj_t * ui_Whitespace2;
lv_obj_t * ui_Space_container;
void ui_event_Finish_button_button(lv_event_t * e);
lv_obj_t * ui_Finish_button;
lv_obj_t * ui_Cardbg_ghostbtn2;
lv_obj_t * ui_Cardbg_animcontainer9;
lv_obj_t * ui_Cardbg1;
lv_obj_t * ui_Charge_bar;
lv_obj_t * ui_Green_panel;
lv_obj_t * ui_Green_startbar2;
lv_obj_t * ui_Blue_panel;
lv_obj_t * ui_Blue_indicator1;
lv_obj_t * ui_Space_panel;
lv_obj_t * ui_Space_bar;
lv_obj_t * ui_Ghostbutton;


// SCREEN: ui_Pricing
void ui_Pricing_screen_init(void);
void ui_event_Pricing(lv_event_t * e);
lv_obj_t * ui_Pricing;
lv_obj_t * ui_Main_group;
lv_obj_t * ui_Full_content5;
lv_obj_t * ui_Main_bg_img8;
lv_obj_t * ui_Statusbar_group4;
lv_obj_t * ui_Contact_icon4;
lv_obj_t * ui_Call_number7;
lv_obj_t * ui_Statusbar_date7;
void ui_event_Back_button7_button(lv_event_t * e);
lv_obj_t * ui_Back_button7;
lv_obj_t * ui_Cardbg_animcontainer1;
lv_obj_t * ui_Cardbg11;
lv_obj_t * ui_Welcoming;
lv_obj_t * ui_Welcoming_label;
lv_obj_t * ui_Welcoming_text;
lv_obj_t * ui_Fee_panel2;
lv_obj_t * ui_Fee_label2;
lv_obj_t * ui_Price_label2;
lv_obj_t * ui_Charging_panel2;
lv_obj_t * ui_Num_label6;
lv_obj_t * ui_Num_label7;
lv_obj_t * ui_Charging_panel3;
lv_obj_t * ui_Charging_speed2;
lv_obj_t * ui_Pos_container;
lv_obj_t * ui_Pos_img;


// SCREEN: ui_Help
void ui_Help_screen_init(void);
void ui_event_Help(lv_event_t * e);
lv_obj_t * ui_Help;
lv_obj_t * ui_Main_group2;
lv_obj_t * ui_Full_content6;
lv_obj_t * ui_Main_bg_img9;
lv_obj_t * ui_Statusbar_group8;
lv_obj_t * ui_Contact_icon8;
lv_obj_t * ui_Call_number8;
lv_obj_t * ui_Statusbar_date8;
void ui_event_Back_button8_button(lv_event_t * e);
lv_obj_t * ui_Back_button8;
lv_obj_t * ui_Cardbg_animcontainer11;
lv_obj_t * ui_Cardbg13;
lv_obj_t * ui_Created_title_;
lv_obj_t * ui_Createdby;
lv_obj_t * ui_SLS1;
lv_obj_t * ui_SLS1_extract;
lv_obj_t * ui_About_sls1;
lv_obj_t * ui_SLS1_offers;
lv_obj_t * ui_Authentication;
lv_obj_t * ui_LVGL_extract;
lv_obj_t * ui_Poweredby;
lv_obj_t * ui_About_lvgl;
lv_obj_t * ui_Qr_container_;
lv_obj_t * ui_Qr2;
void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_bg[1] = {&ui_img_bg4_png};
const lv_img_dsc_t * ui_imgset_qr_code[2] = {&ui_img_qr_code1_png, &ui_img_qr_code2_png};
const lv_img_dsc_t * ui_imgset_slider_bg[3] = {&ui_img_slider_bg1_png, &ui_img_slider_bg2_png, &ui_img_slider_bg3_png};
const lv_img_dsc_t * ui_imgset_slider_mask[2] = {&ui_img_slider_mask1_png, &ui_img_slider_mask2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
/*
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif
*/
///////////////////// ANIMATIONS ////////////////////
void charging1_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 3000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 528);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}
void charging2_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 6000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 577);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}
void charging3_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 10000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 573);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}
void left_on_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 600);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -470, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void left_off_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, -200);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}
void bottom_on_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 400);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 50, -25);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void bottom_off_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, 200);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void phone_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 600);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 200, 40);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}
void big_left_on_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 600);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -200, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void ready_on_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 1800, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 600);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_1, 150, 256);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 300);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_2, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
    lv_anim_set_early_apply(&PropertyAnimation_2, true);
    lv_anim_start(&PropertyAnimation_2);

}
void ready_off_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 200);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_1, 255, 150);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 200);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_2, 0, 900);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_start(&PropertyAnimation_2);

}
void top_on_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 400);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -100, -63);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}
void top_off_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, -60);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}
void end_bar_on_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 400);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 82, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}
void end_bar_off_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 38, 200);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}
void top_on2_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -100, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        left_on_Animation(ui_Cardbg, 0);
        bottom_on_Animation(ui_Start_button, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        left_off_Animation(ui_Cardbg, 0);
        bottom_off_Animation(ui_Start_button, 0);
    }
}
void ui_event_Pricing_group(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pricing, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Pricing_screen_init);
    }
}
void ui_event_Help_group(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Help, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Help_screen_init);
    }
}
void ui_event_Start_button_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Step1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Step1_screen_init);
    }
}
void ui_event_Step1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        left_on_Animation(ui_Cardbg2, 0);
        bottom_on_Animation(ui_Next_button, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        left_off_Animation(ui_Cardbg2, 0);
        bottom_off_Animation(ui_Next_button, 0);
    }
}
void ui_event_Pricing_group2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pricing, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Pricing_screen_init);
    }
}
void ui_event_Help_group2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Help, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Help_screen_init);
    }
}
void ui_event_Next_button_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Step2, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Step2_screen_init);
    }
}
void ui_event_Step2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        bottom_on_Animation(ui_Next_button2, 0);
        left_on_Animation(ui_Cardbg3, 0);
        phone_Animation(ui_Phone, 0);
        top_on_Animation(ui_Qr, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        left_off_Animation(ui_Cardbg3, 0);
        bottom_off_Animation(ui_Next_button2, 0);
        bottom_off_Animation(ui_Phone, 100);
        top_off_Animation(ui_Qr, 0);
    }
}
void ui_event_Pricing_group3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pricing, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Pricing_screen_init);
    }
}
void ui_event_help_group3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Help, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Help_screen_init);
    }
}
void ui_event_Next_button2_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Connect, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Connect_screen_init);
    }
}
void ui_event_Connect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_Cardbg4, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        bottom_off_Animation(ui_Cardbg4, 0);
    }
}
void ui_event_Cardbg4_cardbg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Welcome, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Welcome_screen_init);
    }
}
void ui_event_Welcome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        big_left_on_Animation(ui_Cardbg5, 0);
        bottom_on_Animation(ui_Continue_button, 0);
        ready_on_Animation(ui_ready, 300);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        left_off_Animation(ui_Cardbg5, 0);
        bottom_off_Animation(ui_Continue_button, 0);
        ready_off_Animation(ui_ready, 0);
    }
}
void ui_event_Continue_button_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Charging, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Charging_screen_init);
    }
}
void ui_event_Charging(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_Stop_button, 0);
        top_on2_Animation(ui_Cardbg_container, 100);
        bottom_on_Animation(ui_Charging_speed_group, 100);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        bottom_off_Animation(ui_Stop_button, 0);
        top_off_Animation(ui_Cardbg_container, 50);
        top_off_Animation(ui_Charging_energie_group, 0);
        bottom_off_Animation(ui_Charging_speed_group, 100);
    }
}
void ui_event_Stop_button_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_End, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_End_screen_init);
    }
}
void ui_event_End(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_Finish_button, 0);
        left_on_Animation(ui_Full_chart_group, 0);
        top_on2_Animation(ui_Cardbg7, 100);
        bottom_on_Animation(ui_Cardbg1, 100);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        bottom_off_Animation(ui_Finish_button, 0);
        left_off_Animation(ui_Full_chart_group, 0);
        top_off_Animation(ui_Cardbg7, 100);
        bottom_off_Animation(ui_Cardbg1, 100);
    }
}
void ui_event_Finish_button_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Home_screen_init);
    }
}
void ui_event_Pricing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_Back_button7, 0);
        ready_on_Animation(ui_Pos_img, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        bottom_off_Animation(ui_Back_button7, 0);
        ready_off_Animation(ui_Pos_img, 0);
    }
}
void ui_event_Back_button7_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Home_screen_init);
    }
}
void ui_event_Help(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_Back_button8, 0);
        ready_on_Animation(ui_Qr2, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        bottom_off_Animation(ui_Back_button8, 0);
        ready_off_Animation(ui_Qr2, 0);
    }
}
void ui_event_Back_button8_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Home_screen_init);
    }
}
void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        charging1_Animation(ui_Anim_bg1, 0);
        charging2_Animation(ui_Anim_bg2, 0);
        charging3_Animation(ui_Anim_bg3, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_Step1_screen_init();
    ui_Step2_screen_init();
    ui_Connect_screen_init();
    ui_Welcome_screen_init();
    ui_Charging_screen_init();
    ui_End_screen_init();
    ui_Pricing_screen_init();
    ui_Help_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_Home);
}
