// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EV_Charger

#ifndef _EV_CHARGER_UI_H
#define _EV_CHARGER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

void charging1_Animation(lv_obj_t * TargetObject, int delay);
void charging2_Animation(lv_obj_t * TargetObject, int delay);
void charging3_Animation(lv_obj_t * TargetObject, int delay);
void left_on_Animation(lv_obj_t * TargetObject, int delay);
void left_off_Animation(lv_obj_t * TargetObject, int delay);
void bottom_on_Animation(lv_obj_t * TargetObject, int delay);
void bottom_off_Animation(lv_obj_t * TargetObject, int delay);
void phone_Animation(lv_obj_t * TargetObject, int delay);
void big_left_on_Animation(lv_obj_t * TargetObject, int delay);
void ready_on_Animation(lv_obj_t * TargetObject, int delay);
void ready_off_Animation(lv_obj_t * TargetObject, int delay);
void top_on_Animation(lv_obj_t * TargetObject, int delay);
void top_off_Animation(lv_obj_t * TargetObject, int delay);
void end_bar_on_Animation(lv_obj_t * TargetObject, int delay);
void end_bar_off_Animation(lv_obj_t * TargetObject, int delay);
void top_on2_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Full_content_group;
extern lv_obj_t * ui_Slidebar;
extern lv_obj_t * ui_Slidebar_bg;
void ui_event_Pricing_group(lv_event_t * e);
extern lv_obj_t * ui_Pricing_group;
extern lv_obj_t * ui_Pricing_icon;
extern lv_obj_t * ui_Pricing_label;
void ui_event_Help_group(lv_event_t * e);
extern lv_obj_t * ui_Help_group;
extern lv_obj_t * ui_Help_icon;
extern lv_obj_t * ui_Help_label;
extern lv_obj_t * ui_Content_of_objects;
extern lv_obj_t * ui_Main_bg_img;
extern lv_obj_t * ui_Statusbar_group;
extern lv_obj_t * ui_Contact_icon;
extern lv_obj_t * ui_Call_number;
extern lv_obj_t * ui_Statusbar_date;
extern lv_obj_t * ui_Bottom_charger_id;
extern lv_obj_t * ui_Cardbg_animcontainer;
extern lv_obj_t * ui_Cardbg;
extern lv_obj_t * ui_Welcome_title;
extern lv_obj_t * ui_Charger_extract;
extern lv_obj_t * ui_Started_h1;
extern lv_obj_t * ui_carimg;
void ui_event_Start_button_button(lv_event_t * e);
extern lv_obj_t * ui_Start_button;
// SCREEN: ui_Step1
void ui_Step1_screen_init(void);
void ui_event_Step1(lv_event_t * e);
extern lv_obj_t * ui_Step1;
extern lv_obj_t * ui_Full_content2;
extern lv_obj_t * ui_Slidebar2;
extern lv_obj_t * ui_Slidebar_bg_;
void ui_event_Pricing_group2(lv_event_t * e);
extern lv_obj_t * ui_Pricing_group2;
extern lv_obj_t * ui_Pricing_icon2;
extern lv_obj_t * ui_Pricing_label2;
void ui_event_Help_group2(lv_event_t * e);
extern lv_obj_t * ui_Help_group2;
extern lv_obj_t * ui_Help_icon2;
extern lv_obj_t * ui_Help_label2;
extern lv_obj_t * ui_Content_of_objects2;
extern lv_obj_t * ui_Main_bg_img2;
extern lv_obj_t * ui_Statusbar_group2;
extern lv_obj_t * ui_Contact_icon2;
extern lv_obj_t * ui_Call_number2;
extern lv_obj_t * ui_Statusbar_date2;
extern lv_obj_t * ui_Cardbg_animcontainer2;
extern lv_obj_t * ui_Cardbg2;
extern lv_obj_t * ui_Step_labels;
extern lv_obj_t * ui_One_icon;
extern lv_obj_t * ui_Step;
extern lv_obj_t * ui_Plugin_h2;
extern lv_obj_t * ui_First_step;
extern lv_obj_t * ui_plug;
void ui_event_Next_button_button(lv_event_t * e);
extern lv_obj_t * ui_Next_button;
extern lv_obj_t * ui_Plagination;
extern lv_obj_t * ui_one_gray;
extern lv_obj_t * ui_two_black;
// SCREEN: ui_Step2
void ui_Step2_screen_init(void);
void ui_event_Step2(lv_event_t * e);
extern lv_obj_t * ui_Step2;
extern lv_obj_t * ui_Full_content3;
extern lv_obj_t * ui_Slidebar3;
extern lv_obj_t * ui_Slidebar_bg2;
void ui_event_Pricing_group3(lv_event_t * e);
extern lv_obj_t * ui_Pricing_group3;
extern lv_obj_t * ui_Pricing_icon3;
extern lv_obj_t * ui_Pricing_label3;
void ui_event_help_group3(lv_event_t * e);
extern lv_obj_t * ui_help_group3;
extern lv_obj_t * ui_Help_icon3;
extern lv_obj_t * ui_Help_label3;
extern lv_obj_t * ui_Content_of_objects3;
extern lv_obj_t * ui_Main_bg_img3;
extern lv_obj_t * ui_Statusbar_group3;
extern lv_obj_t * ui_Contact_icon3;
extern lv_obj_t * ui_Call_number3;
extern lv_obj_t * ui_Statusbar_date3;
extern lv_obj_t * ui_Authentication_text;
extern lv_obj_t * ui_Cardbg_animcontainer3;
extern lv_obj_t * ui_Cardbg3;
extern lv_obj_t * ui_Step_labels2;
extern lv_obj_t * ui_Two_icon;
extern lv_obj_t * ui_Step3;
extern lv_obj_t * ui_Authentication_h5;
extern lv_obj_t * ui_Phone;
extern lv_obj_t * ui_Plagination2;
extern lv_obj_t * ui_Two_gray_;
extern lv_obj_t * ui_Two_black;
extern lv_obj_t * ui_Qr_container;
extern lv_obj_t * ui_Qr;
void ui_event_Next_button2_button(lv_event_t * e);
extern lv_obj_t * ui_Next_button2;
// SCREEN: ui_Connect
void ui_Connect_screen_init(void);
void ui_event_Connect(lv_event_t * e);
extern lv_obj_t * ui_Connect;
extern lv_obj_t * ui_Main_bg_img4;
extern lv_obj_t * ui_Helptext;
extern lv_obj_t * ui_Cardbg_animcontainer4;
void ui_event_Cardbg4_cardbg(lv_event_t * e);
extern lv_obj_t * ui_Cardbg4;
extern lv_obj_t * ui_Connecting_Container;
extern lv_obj_t * ui_Waiting_title;
extern lv_obj_t * ui_Connecting_h3;
extern lv_obj_t * ui_Spinner;
// SCREEN: ui_Welcome
void ui_Welcome_screen_init(void);
void ui_event_Welcome(lv_event_t * e);
extern lv_obj_t * ui_Welcome;
extern lv_obj_t * ui_Main_bg_img5;
extern lv_obj_t * ui_Cardbg_animcontainer5;
extern lv_obj_t * ui_Cardbg5;
extern lv_obj_t * ui_Welcome_panel;
extern lv_obj_t * ui_Welcomimg_title;
extern lv_obj_t * ui_Welcome_text;
extern lv_obj_t * ui_Fee_panel;
extern lv_obj_t * ui_Fee_label;
extern lv_obj_t * ui_Price_fee;
extern lv_obj_t * ui_Charging_panel;
extern lv_obj_t * ui_Charging_text;
extern lv_obj_t * ui_Amount_text;
extern lv_obj_t * ui_Charging_speed_panel;
extern lv_obj_t * ui_Charging_speed;
extern lv_obj_t * ui_Full_content;
extern lv_obj_t * ui_Content_of_objects5;
extern lv_obj_t * ui_Statusbar_date5;
extern lv_obj_t * ui_Statusbar_group5;
extern lv_obj_t * ui_Contact_icon5;
extern lv_obj_t * ui_Call_number5;
extern lv_obj_t * ui_Ready_img_container;
extern lv_obj_t * ui_ready;
void ui_event_Continue_button_button(lv_event_t * e);
extern lv_obj_t * ui_Continue_button;
// SCREEN: ui_Charging
void ui_Charging_screen_init(void);
void ui_event_Charging(lv_event_t * e);
extern lv_obj_t * ui_Charging;
extern lv_obj_t * ui_Main_bg_img6;
extern lv_obj_t * ui_Full_content1;
extern lv_obj_t * ui_Statusbar_group6;
extern lv_obj_t * ui_Statusbar_info;
extern lv_obj_t * ui_Contact_icon6;
extern lv_obj_t * ui_Call_number6;
extern lv_obj_t * ui_Statusbar_date6;
extern lv_obj_t * ui_Space;
extern lv_obj_t * ui_Cardbg_animcontainer6;
extern lv_obj_t * ui_Cardbg_container;
extern lv_obj_t * ui_Charging_time_group;
extern lv_obj_t * ui_Charging_time;
extern lv_obj_t * ui_Label_charging;
extern lv_obj_t * ui_Amount_group;
extern lv_obj_t * ui_Num_label;
extern lv_obj_t * ui_Min_label;
extern lv_obj_t * ui_Charging_cost_group;
extern lv_obj_t * ui_Charging_cost;
extern lv_obj_t * ui_Label_cost;
extern lv_obj_t * ui_Amount_group2;
extern lv_obj_t * ui_Price_label;
extern lv_obj_t * ui_Charging_energie_group;
extern lv_obj_t * ui_Energy_del;
extern lv_obj_t * ui_Label_energy;
extern lv_obj_t * ui_Amount_group3;
extern lv_obj_t * ui_Num_label2;
extern lv_obj_t * ui_Kwh_label;
extern lv_obj_t * ui_Main_chargercontainer;
extern lv_obj_t * ui_State;
extern lv_obj_t * ui_Full_charger_group;
extern lv_obj_t * ui_Cardbg6;
extern lv_obj_t * ui_Anim_bg2;
extern lv_obj_t * ui_Anim_bg3;
extern lv_obj_t * ui_Anim_bg1;
extern lv_obj_t * ui_Mask1;
extern lv_obj_t * ui_Mask2;
extern lv_obj_t * ui_Chargebar_fr_cont;
extern lv_obj_t * ui_Green_startbar;
extern lv_obj_t * ui_Startbar_indicator;
extern lv_obj_t * ui_Blue_indicator;
extern lv_obj_t * ui_Whitespace_2fr;
extern lv_obj_t * ui_Percent_nums;
extern lv_obj_t * ui_Percent_num1;
extern lv_obj_t * ui_Percent_num2;
extern lv_obj_t * ui_Whitespace1;
extern lv_obj_t * ui_Cardbg_ghostbtn;
extern lv_obj_t * ui_Cardbg_animcontainer7;
extern lv_obj_t * ui_Charging_speed_group;
extern lv_obj_t * ui_Speed_label;
extern lv_obj_t * ui_Speed_group;
extern lv_obj_t * ui_Num_label3;
extern lv_obj_t * ui_Kw_;
extern lv_obj_t * ui_Whitespace_ghostbtn;
void ui_event_Stop_button_button(lv_event_t * e);
extern lv_obj_t * ui_Stop_button;
// SCREEN: ui_End
void ui_End_screen_init(void);
void ui_event_End(lv_event_t * e);
extern lv_obj_t * ui_End;
extern lv_obj_t * ui_Main_bg_img7;
extern lv_obj_t * ui_Full_content4;
extern lv_obj_t * ui_Statusbar_group7;
extern lv_obj_t * ui_Statusbar_info6;
extern lv_obj_t * ui_Contact_icon7;
extern lv_obj_t * ui_Call_number1;
extern lv_obj_t * ui_Statusbar_date1;
extern lv_obj_t * ui_Two_columns;
extern lv_obj_t * ui_Chart_animcontainer;
extern lv_obj_t * ui_Full_chart_group;
extern lv_obj_t * ui_Chart;
extern lv_obj_t * ui_Total_label;
extern lv_obj_t * ui_Time_label;
extern lv_obj_t * ui_Cardbg_and_sum_;
extern lv_obj_t * ui_Cardbg_animcontainer8;
extern lv_obj_t * ui_Cardbg7;
extern lv_obj_t * ui_Fee_group;
extern lv_obj_t * ui_Total_label2;
extern lv_obj_t * ui_Num_label4;
extern lv_obj_t * ui_Fee_group2;
extern lv_obj_t * ui_Time_label2;
extern lv_obj_t * ui_Num_label5;
extern lv_obj_t * ui_Sum_container;
extern lv_obj_t * ui_Summary_price;
extern lv_obj_t * ui_Total_cost;
extern lv_obj_t * ui_Whitespace2;
extern lv_obj_t * ui_Space_container;
void ui_event_Finish_button_button(lv_event_t * e);
extern lv_obj_t * ui_Finish_button;
extern lv_obj_t * ui_Cardbg_ghostbtn2;
extern lv_obj_t * ui_Cardbg_animcontainer9;
extern lv_obj_t * ui_Cardbg1;
extern lv_obj_t * ui_Charge_bar;
extern lv_obj_t * ui_Green_panel;
extern lv_obj_t * ui_Green_startbar2;
extern lv_obj_t * ui_Blue_panel;
extern lv_obj_t * ui_Blue_indicator1;
extern lv_obj_t * ui_Space_panel;
extern lv_obj_t * ui_Space_bar;
extern lv_obj_t * ui_Ghostbutton;
// SCREEN: ui_Pricing
void ui_Pricing_screen_init(void);
void ui_event_Pricing(lv_event_t * e);
extern lv_obj_t * ui_Pricing;
extern lv_obj_t * ui_Main_group;
extern lv_obj_t * ui_Full_content5;
extern lv_obj_t * ui_Main_bg_img8;
extern lv_obj_t * ui_Statusbar_group4;
extern lv_obj_t * ui_Contact_icon4;
extern lv_obj_t * ui_Call_number7;
extern lv_obj_t * ui_Statusbar_date7;
void ui_event_Back_button7_button(lv_event_t * e);
extern lv_obj_t * ui_Back_button7;
extern lv_obj_t * ui_Cardbg_animcontainer1;
extern lv_obj_t * ui_Cardbg11;
extern lv_obj_t * ui_Welcoming;
extern lv_obj_t * ui_Welcoming_label;
extern lv_obj_t * ui_Welcoming_text;
extern lv_obj_t * ui_Fee_panel2;
extern lv_obj_t * ui_Fee_label2;
extern lv_obj_t * ui_Price_label2;
extern lv_obj_t * ui_Charging_panel2;
extern lv_obj_t * ui_Num_label6;
extern lv_obj_t * ui_Num_label7;
extern lv_obj_t * ui_Charging_panel3;
extern lv_obj_t * ui_Charging_speed2;
extern lv_obj_t * ui_Pos_container;
extern lv_obj_t * ui_Pos_img;
// SCREEN: ui_Help
void ui_Help_screen_init(void);
void ui_event_Help(lv_event_t * e);
extern lv_obj_t * ui_Help;
extern lv_obj_t * ui_Main_group2;
extern lv_obj_t * ui_Full_content6;
extern lv_obj_t * ui_Main_bg_img9;
extern lv_obj_t * ui_Statusbar_group8;
extern lv_obj_t * ui_Contact_icon8;
extern lv_obj_t * ui_Call_number8;
extern lv_obj_t * ui_Statusbar_date8;
void ui_event_Back_button8_button(lv_event_t * e);
extern lv_obj_t * ui_Back_button8;
extern lv_obj_t * ui_Cardbg_animcontainer11;
extern lv_obj_t * ui_Cardbg13;
extern lv_obj_t * ui_Created_title_;
extern lv_obj_t * ui_Createdby;
extern lv_obj_t * ui_SLS1;
extern lv_obj_t * ui_SLS1_extract;
extern lv_obj_t * ui_About_sls1;
extern lv_obj_t * ui_SLS1_offers;
extern lv_obj_t * ui_Authentication;
extern lv_obj_t * ui_LVGL_extract;
extern lv_obj_t * ui_Poweredby;
extern lv_obj_t * ui_About_lvgl;
extern lv_obj_t * ui_Qr_container_;
extern lv_obj_t * ui_Qr2;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_left_side_png);    // assets/left_side.png
LV_IMG_DECLARE(ui_img_pricing_png);    // assets/pricing.png
LV_IMG_DECLARE(ui_img_help_png);    // assets/help.png
LV_IMG_DECLARE(ui_img_bg4_png);    // assets/bg4.png
LV_IMG_DECLARE(ui_img_contact_png);    // assets/contact.png
LV_IMG_DECLARE(ui_img_s1_car_png);    // assets/s1_car.png
LV_IMG_DECLARE(ui_img_plug_png);    // assets/plug.png
LV_IMG_DECLARE(ui_img_phone_png);    // assets/phone.png
LV_IMG_DECLARE(ui_img_qr_code1_png);    // assets/qr_code1.png
LV_IMG_DECLARE(ui_img_time_png);    // assets/time.png
LV_IMG_DECLARE(ui_img_ok_png);    // assets/ok.png
LV_IMG_DECLARE(ui_img_slider_bg2_png);    // assets/slider_bg2.png
LV_IMG_DECLARE(ui_img_slider_bg3_png);    // assets/slider_bg3.png
LV_IMG_DECLARE(ui_img_slider_bg1_png);    // assets/slider_bg1.png
LV_IMG_DECLARE(ui_img_slider_mask2_png);    // assets/slider_mask2.png
LV_IMG_DECLARE(ui_img_slider_mask1_png);    // assets/slider_mask1.png
LV_IMG_DECLARE(ui_img_pos_png);    // assets/pos.png
LV_IMG_DECLARE(ui_img_qr_code2_png);    // assets/qr_code2.png



LV_FONT_DECLARE(ui_font_Bold);
LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_H2);
LV_FONT_DECLARE(ui_font_Light);
LV_FONT_DECLARE(ui_font_Number);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
