// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "ui.h"

void ui_Connect_screen_init(void)
{
    ui_Connect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Connect, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_bg_img4 = lv_img_create(ui_Connect);
    lv_img_set_src(ui_Main_bg_img4, &ui_img_bg4_png);
    lv_obj_set_width(ui_Main_bg_img4, LV_SIZE_CONTENT);   /// 640
    lv_obj_set_height(ui_Main_bg_img4, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_align(ui_Main_bg_img4, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Main_bg_img4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Main_bg_img4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Helptext = lv_label_create(ui_Connect);
    lv_obj_set_width(ui_Helptext, 555);
    lv_obj_set_height(ui_Helptext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Helptext, 0);
    lv_obj_set_y(ui_Helptext, -31);
    lv_obj_set_align(ui_Helptext, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Helptext,
                      "If the connection with the vehicle is failed, the process will be terminated automatically.");
    lv_obj_set_style_text_color(ui_Helptext, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Helptext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Helptext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Helptext, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg_animcontainer4 = lv_obj_create(ui_Connect);
    lv_obj_set_width(ui_Cardbg_animcontainer4, lv_pct(90));
    lv_obj_set_height(ui_Cardbg_animcontainer4, lv_pct(77));
    lv_obj_set_align(ui_Cardbg_animcontainer4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Cardbg_animcontainer4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Cardbg_animcontainer4, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cardbg_animcontainer4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg4 = ui_cardbg_create(ui_Cardbg_animcontainer4);
    lv_obj_set_width(ui_Cardbg4, lv_pct(79));
    lv_obj_set_height(ui_Cardbg4, lv_pct(72));
    lv_obj_set_x(ui_Cardbg4, 1);
    lv_obj_set_y(ui_Cardbg4, -12);
    lv_obj_set_flex_flow(ui_Cardbg4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Cardbg4, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_Cardbg4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Connecting_Container = lv_obj_create(ui_Cardbg4);
    lv_obj_remove_style_all(ui_Connecting_Container);
    lv_obj_set_width(ui_Connecting_Container, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Connecting_Container, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Connecting_Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Connecting_Container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Connecting_Container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Connecting_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Waiting_title = lv_label_create(ui_Connecting_Container);
    lv_obj_set_width(ui_Waiting_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Waiting_title, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Waiting_title, "Please wait...");
    lv_obj_set_style_text_color(ui_Waiting_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Waiting_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waiting_title, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Connecting_h3 = lv_label_create(ui_Connecting_Container);
    lv_obj_set_width(ui_Connecting_h3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Connecting_h3, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Connecting_h3, 17);
    lv_obj_set_y(ui_Connecting_h3, -182);
    lv_label_set_text(ui_Connecting_h3, "Connecting\nto vehicle");
    lv_obj_set_style_text_color(ui_Connecting_h3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Connecting_h3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Connecting_h3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Connecting_h3, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Connecting_h3, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner = lv_spinner_create(ui_Cardbg4, 1000, 90);
    lv_obj_set_width(ui_Spinner, 120);
    lv_obj_set_height(ui_Spinner, 120);
    lv_obj_set_align(ui_Spinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Spinner, &ui_img_time_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0x3D3C50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0x1F8BFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Cardbg4, ui_event_Cardbg4_cardbg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Connect, ui_event_Connect, LV_EVENT_ALL, NULL);

}
