// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "ui.h"

void ui_Charging_screen_init(void)
{
    ui_Charging = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Charging, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Charging, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Charging, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_bg_img6 = lv_img_create(ui_Charging);
    lv_img_set_src(ui_Main_bg_img6, &ui_img_bg4_png);
    lv_obj_set_width(ui_Main_bg_img6, LV_SIZE_CONTENT);   /// 640
    lv_obj_set_height(ui_Main_bg_img6, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_align(ui_Main_bg_img6, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Main_bg_img6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Main_bg_img6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Full_content1 = lv_obj_create(ui_Charging);
    lv_obj_set_width(ui_Full_content1, lv_pct(100));
    lv_obj_set_height(ui_Full_content1, lv_pct(100));
    lv_obj_set_align(ui_Full_content1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Full_content1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Full_content1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Full_content1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_content1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_content1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_group6 = lv_obj_create(ui_Full_content1);
    lv_obj_remove_style_all(ui_Statusbar_group6);
    lv_obj_set_height(ui_Statusbar_group6, 31);
    lv_obj_set_width(ui_Statusbar_group6, lv_pct(100));
    lv_obj_set_align(ui_Statusbar_group6, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Statusbar_group6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Statusbar_group6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Statusbar_group6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Statusbar_group6, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Statusbar_group6, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Statusbar_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Statusbar_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_info = lv_obj_create(ui_Statusbar_group6);
    lv_obj_set_width(ui_Statusbar_info, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Statusbar_info, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_Statusbar_info, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Statusbar_info, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Statusbar_info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Statusbar_info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Statusbar_info, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Statusbar_info, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Statusbar_info, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Contact_icon6 = lv_img_create(ui_Statusbar_info);
    lv_img_set_src(ui_Contact_icon6, &ui_img_contact_png);
    lv_obj_set_width(ui_Contact_icon6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Contact_icon6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Contact_icon6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Contact_icon6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Contact_icon6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Call_number6 = lv_label_create(ui_Statusbar_info);
    lv_obj_set_width(ui_Call_number6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Call_number6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Call_number6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Call_number6, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_Call_number6, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Call_number6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Call_number6, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_date6 = lv_label_create(ui_Statusbar_group6);
    lv_obj_set_width(ui_Statusbar_date6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Statusbar_date6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Statusbar_date6, 0);
    lv_obj_set_y(ui_Statusbar_date6, 1);
    lv_obj_set_align(ui_Statusbar_date6, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Statusbar_date6, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_Statusbar_date6, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Statusbar_date6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Statusbar_date6, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Space = lv_obj_create(ui_Full_content1);
    lv_obj_remove_style_all(ui_Space);
    lv_obj_set_height(ui_Space, 10);
    lv_obj_set_width(ui_Space, lv_pct(100));
    lv_obj_set_align(ui_Space, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Space, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Cardbg_animcontainer6 = lv_obj_create(ui_Full_content1);
    lv_obj_remove_style_all(ui_Cardbg_animcontainer6);
    lv_obj_set_width(ui_Cardbg_animcontainer6, lv_pct(100));
    lv_obj_set_flex_grow(ui_Cardbg_animcontainer6, 1);
    lv_obj_set_x(ui_Cardbg_animcontainer6, 0);
    lv_obj_set_y(ui_Cardbg_animcontainer6, 30);
    lv_obj_set_align(ui_Cardbg_animcontainer6, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Cardbg_animcontainer6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Cardbg_animcontainer6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_animcontainer6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_animcontainer6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_animcontainer6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Cardbg_animcontainer6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Cardbg_animcontainer6, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg_container = lv_obj_create(ui_Cardbg_animcontainer6);
    lv_obj_remove_style_all(ui_Cardbg_container);
    lv_obj_set_width(ui_Cardbg_container, lv_pct(100));
    lv_obj_set_height(ui_Cardbg_container, lv_pct(100));
    lv_obj_set_align(ui_Cardbg_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Cardbg_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Cardbg_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Cardbg_container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Cardbg_container, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_container, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Cardbg_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Cardbg_container, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_time_group = ui_cardbg_create(ui_Cardbg_container);
    lv_obj_set_height(ui_Charging_time_group, lv_pct(88));
    lv_obj_set_flex_grow(ui_Charging_time_group, 1);
    lv_obj_set_x(ui_Charging_time_group, 0);
    lv_obj_set_y(ui_Charging_time_group, 30);
    lv_obj_set_align(ui_Charging_time_group, LV_ALIGN_TOP_LEFT);
    lv_obj_set_flex_flow(ui_Charging_time_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Charging_time_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_Charging_time_group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Charging_time_group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Charging_time_group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Charging_time_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Charging_time_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Charging_time_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_time = lv_obj_create(ui_Charging_time_group);
    lv_obj_set_width(ui_Charging_time, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Charging_time, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_align(ui_Charging_time, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Charging_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Charging_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Charging_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_charging = lv_label_create(ui_Charging_time);
    lv_obj_set_width(ui_Label_charging, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_charging, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_charging, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_charging, "Charging time");
    lv_obj_set_style_text_color(ui_Label_charging, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_charging, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_charging, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Amount_group = lv_obj_create(ui_Charging_time_group);
    lv_obj_set_width(ui_Amount_group, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Amount_group, LV_SIZE_CONTENT);    /// 94
    lv_obj_set_align(ui_Amount_group, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Amount_group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Amount_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Amount_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Amount_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Amount_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Amount_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Amount_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Num_label = lv_label_create(ui_Amount_group);
    lv_obj_set_width(ui_Num_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Num_label, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_align(ui_Num_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Num_label, "28");
    lv_obj_set_style_text_color(ui_Num_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Num_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Num_label, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Min_label = lv_label_create(ui_Amount_group);
    lv_obj_set_height(ui_Min_label, 30);
    lv_obj_set_width(ui_Min_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Min_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Min_label, "MIN");
    lv_obj_set_style_text_color(ui_Min_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Min_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Min_label, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_cost_group = ui_cardbg_create(ui_Cardbg_container);
    lv_obj_set_height(ui_Charging_cost_group, lv_pct(88));
    lv_obj_set_flex_grow(ui_Charging_cost_group, 1);
    lv_obj_set_x(ui_Charging_cost_group, 0);
    lv_obj_set_y(ui_Charging_cost_group, 30);
    lv_obj_set_align(ui_Charging_cost_group, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Charging_cost_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Charging_cost_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_Charging_cost_group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Charging_cost_group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Charging_cost_group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Charging_cost_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Charging_cost_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Charging_cost_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_cost = lv_obj_create(ui_Charging_cost_group);
    lv_obj_set_width(ui_Charging_cost, lv_pct(100));
    lv_obj_set_height(ui_Charging_cost, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Charging_cost, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Charging_cost, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Charging_cost, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Charging_cost, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_cost = lv_label_create(ui_Charging_cost);
    lv_obj_set_width(ui_Label_cost, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_cost, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_cost, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_cost, "Charging cost");
    lv_obj_set_style_text_color(ui_Label_cost, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_cost, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_cost, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Amount_group2 = lv_obj_create(ui_Charging_cost_group);
    lv_obj_set_width(ui_Amount_group2, lv_pct(100));
    lv_obj_set_height(ui_Amount_group2, LV_SIZE_CONTENT);    /// 94
    lv_obj_set_align(ui_Amount_group2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Amount_group2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Amount_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Amount_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Amount_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Amount_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Amount_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Amount_group2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Price_label = lv_label_create(ui_Amount_group2);
    lv_obj_set_width(ui_Price_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Price_label, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_align(ui_Price_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Price_label, "$34.25");
    lv_obj_set_style_text_color(ui_Price_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Price_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Price_label, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_energie_group = ui_cardbg_create(ui_Cardbg_container);
    lv_obj_set_height(ui_Charging_energie_group, lv_pct(88));
    lv_obj_set_flex_grow(ui_Charging_energie_group, 1);
    lv_obj_set_x(ui_Charging_energie_group, 0);
    lv_obj_set_y(ui_Charging_energie_group, 30);
    lv_obj_set_align(ui_Charging_energie_group, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Charging_energie_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Charging_energie_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_Charging_energie_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Charging_energie_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Charging_energie_group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Charging_energie_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Charging_energie_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Charging_energie_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Energy_del = lv_obj_create(ui_Charging_energie_group);
    lv_obj_set_width(ui_Energy_del, lv_pct(100));
    lv_obj_set_height(ui_Energy_del, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Energy_del, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Energy_del, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Energy_del, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Energy_del, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_energy = lv_label_create(ui_Energy_del);
    lv_obj_set_width(ui_Label_energy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_energy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_energy, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_energy, "Energy delivered");
    lv_obj_set_style_text_color(ui_Label_energy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_energy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_energy, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Amount_group3 = lv_obj_create(ui_Charging_energie_group);
    lv_obj_set_width(ui_Amount_group3, lv_pct(100));
    lv_obj_set_height(ui_Amount_group3, LV_SIZE_CONTENT);    /// 108
    lv_obj_set_align(ui_Amount_group3, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Amount_group3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Amount_group3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Amount_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Amount_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Amount_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Amount_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Amount_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Num_label2 = lv_label_create(ui_Amount_group3);
    lv_obj_set_width(ui_Num_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Num_label2, LV_SIZE_CONTENT);    /// 84
    lv_obj_set_align(ui_Num_label2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Num_label2, "84.89");
    lv_obj_set_style_text_color(ui_Num_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Num_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Num_label2, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Kwh_label = lv_label_create(ui_Amount_group3);
    lv_obj_set_height(ui_Kwh_label, 30);
    lv_obj_set_width(ui_Kwh_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Kwh_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Kwh_label, "kWh");
    lv_obj_set_style_text_color(ui_Kwh_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Kwh_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Kwh_label, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_chargercontainer = lv_obj_create(ui_Full_content1);
    lv_obj_remove_style_all(ui_Main_chargercontainer);
    lv_obj_set_width(ui_Main_chargercontainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_Main_chargercontainer, 1);
    lv_obj_set_x(ui_Main_chargercontainer, 0);
    lv_obj_set_y(ui_Main_chargercontainer, -32);
    lv_obj_set_align(ui_Main_chargercontainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_chargercontainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Main_chargercontainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Main_chargercontainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Main_chargercontainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Main_chargercontainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Main_chargercontainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Main_chargercontainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Main_chargercontainer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Main_chargercontainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_State = lv_label_create(ui_Main_chargercontainer);
    lv_obj_set_width(ui_State, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_State, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_State, LV_ALIGN_CENTER);
    lv_label_set_text(ui_State, "State of charge");
    lv_obj_set_style_text_color(ui_State, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_State, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_State, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Full_charger_group = lv_obj_create(ui_Main_chargercontainer);
    lv_obj_set_width(ui_Full_charger_group, lv_pct(100));
    lv_obj_set_height(ui_Full_charger_group, lv_pct(75));
    lv_obj_set_x(ui_Full_charger_group, 0);
    lv_obj_set_y(ui_Full_charger_group, 70);
    lv_obj_set_align(ui_Full_charger_group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Full_charger_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_charger_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_charger_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg6 = ui_cardbg_create(ui_Full_charger_group);
    lv_obj_set_width(ui_Cardbg6, lv_pct(96));
    lv_obj_set_height(ui_Cardbg6, lv_pct(100));
    lv_obj_set_x(ui_Cardbg6, 0);
    lv_obj_set_y(ui_Cardbg6, 0);
    lv_obj_set_align(ui_Cardbg6, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_Cardbg6, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Cardbg6, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Cardbg6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Anim_bg2 = lv_img_create(ui_Cardbg6);
    lv_img_set_src(ui_Anim_bg2, &ui_img_slider_bg2_png);
    lv_obj_set_width(ui_Anim_bg2, lv_pct(150));
    lv_obj_set_height(ui_Anim_bg2, lv_pct(100));
    lv_obj_set_align(ui_Anim_bg2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Anim_bg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Anim_bg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Anim_bg2, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Anim_bg3 = lv_img_create(ui_Cardbg6);
    lv_img_set_src(ui_Anim_bg3, &ui_img_slider_bg3_png);
    lv_obj_set_width(ui_Anim_bg3, lv_pct(150));
    lv_obj_set_height(ui_Anim_bg3, lv_pct(100));
    lv_obj_set_align(ui_Anim_bg3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Anim_bg3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Anim_bg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Anim_bg3, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Anim_bg1 = lv_img_create(ui_Cardbg6);
    lv_img_set_src(ui_Anim_bg1, &ui_img_slider_bg1_png);
    lv_obj_set_width(ui_Anim_bg1, lv_pct(150));
    lv_obj_set_height(ui_Anim_bg1, lv_pct(100));
    lv_obj_set_align(ui_Anim_bg1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Anim_bg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Anim_bg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Anim_bg1, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mask1 = lv_img_create(ui_Cardbg6);
    lv_img_set_src(ui_Mask1, &ui_img_slider_mask2_png);
    lv_obj_set_height(ui_Mask1, 80);
    lv_obj_set_width(ui_Mask1, lv_pct(100));
    lv_obj_set_align(ui_Mask1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Mask1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Mask1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Mask2 = lv_img_create(ui_Cardbg6);
    lv_img_set_src(ui_Mask2, &ui_img_slider_mask1_png);
    lv_obj_set_height(ui_Mask2, 81);
    lv_obj_set_width(ui_Mask2, lv_pct(100));
    lv_obj_set_align(ui_Mask2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Mask2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Mask2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chargebar_fr_cont = lv_obj_create(ui_Full_charger_group);
    lv_obj_set_width(ui_Chargebar_fr_cont, lv_pct(96));
    lv_obj_set_height(ui_Chargebar_fr_cont, lv_pct(100));
    lv_obj_set_align(ui_Chargebar_fr_cont, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Chargebar_fr_cont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Chargebar_fr_cont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Chargebar_fr_cont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Chargebar_fr_cont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chargebar_fr_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Chargebar_fr_cont, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Chargebar_fr_cont, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Chargebar_fr_cont, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Chargebar_fr_cont, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Chargebar_fr_cont, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Chargebar_fr_cont, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Green_startbar = lv_obj_create(ui_Chargebar_fr_cont);
    lv_obj_set_height(ui_Green_startbar, lv_pct(100));
    lv_obj_set_flex_grow(ui_Green_startbar, 1);
    lv_obj_set_align(ui_Green_startbar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Green_startbar, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Green_startbar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Green_startbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Green_startbar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Green_startbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Green_startbar, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Green_startbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Startbar_indicator = lv_obj_create(ui_Green_startbar);
    lv_obj_set_width(ui_Startbar_indicator, lv_pct(100));
    lv_obj_set_height(ui_Startbar_indicator, lv_pct(100));
    lv_obj_set_align(ui_Startbar_indicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Startbar_indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Startbar_indicator, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Startbar_indicator, lv_color_hex(0x00B94C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Startbar_indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Startbar_indicator, lv_color_hex(0x05FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Startbar_indicator, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Startbar_indicator, lv_color_hex(0x05FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Startbar_indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Startbar_indicator, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blue_indicator = lv_obj_create(ui_Chargebar_fr_cont);
    lv_obj_set_height(ui_Blue_indicator, lv_pct(100));
    lv_obj_set_flex_grow(ui_Blue_indicator, 2);
    lv_obj_set_x(ui_Blue_indicator, -261);
    lv_obj_set_y(ui_Blue_indicator, -1);
    lv_obj_set_align(ui_Blue_indicator, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Blue_indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Blue_indicator, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Blue_indicator, lv_color_hex(0x0067D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Blue_indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Blue_indicator, lv_color_hex(0x3FBDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Blue_indicator, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Blue_indicator, lv_color_hex(0x3FCFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Blue_indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Blue_indicator, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Whitespace_2fr = lv_obj_create(ui_Chargebar_fr_cont);
    lv_obj_remove_style_all(ui_Whitespace_2fr);
    lv_obj_set_height(ui_Whitespace_2fr, 50);
    lv_obj_set_flex_grow(ui_Whitespace_2fr, 2);
    lv_obj_set_align(ui_Whitespace_2fr, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Whitespace_2fr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Percent_nums = lv_obj_create(ui_Full_charger_group);
    lv_obj_remove_style_all(ui_Percent_nums);
    lv_obj_set_height(ui_Percent_nums, lv_pct(100));
    lv_obj_set_width(ui_Percent_nums, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Percent_nums, 0);
    lv_obj_set_y(ui_Percent_nums, 10);
    lv_obj_set_align(ui_Percent_nums, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Percent_nums, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Percent_num1 = lv_label_create(ui_Percent_nums);
    lv_obj_set_width(ui_Percent_num1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Percent_num1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Percent_num1, 5);
    lv_obj_set_y(ui_Percent_num1, -2);
    lv_obj_set_align(ui_Percent_num1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Percent_num1, "54%");
    lv_obj_set_style_text_color(ui_Percent_num1, lv_color_hex(0x111020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Percent_num1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Percent_num1, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Percent_num2 = lv_label_create(ui_Percent_nums);
    lv_obj_set_width(ui_Percent_num2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Percent_num2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Percent_num2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Percent_num2, "54%");
    lv_obj_set_style_text_color(ui_Percent_num2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Percent_num2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Percent_num2, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Whitespace1 = lv_obj_create(ui_Full_content1);
    lv_obj_remove_style_all(ui_Whitespace1);
    lv_obj_set_height(ui_Whitespace1, 10);
    lv_obj_set_width(ui_Whitespace1, lv_pct(100));
    lv_obj_set_align(ui_Whitespace1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Whitespace1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Cardbg_ghostbtn = lv_obj_create(ui_Full_content1);
    lv_obj_remove_style_all(ui_Cardbg_ghostbtn);
    lv_obj_set_height(ui_Cardbg_ghostbtn, 65);
    lv_obj_set_width(ui_Cardbg_ghostbtn, lv_pct(100));
    lv_obj_set_align(ui_Cardbg_ghostbtn, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_Cardbg_ghostbtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Cardbg_ghostbtn, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Cardbg_ghostbtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Cardbg_ghostbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_ghostbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_ghostbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_ghostbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Cardbg_ghostbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Cardbg_ghostbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg_animcontainer7 = lv_obj_create(ui_Cardbg_ghostbtn);
    lv_obj_remove_style_all(ui_Cardbg_animcontainer7);
    lv_obj_set_height(ui_Cardbg_animcontainer7, 65);
    lv_obj_set_flex_grow(ui_Cardbg_animcontainer7, 1);
    lv_obj_set_align(ui_Cardbg_animcontainer7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Cardbg_animcontainer7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Cardbg_animcontainer7, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_animcontainer7, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_animcontainer7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_animcontainer7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_speed_group = ui_cardbg_create(ui_Cardbg_animcontainer7);
    lv_obj_set_height(ui_Charging_speed_group, 40);
    lv_obj_set_width(ui_Charging_speed_group, lv_pct(100));
    lv_obj_set_x(ui_Charging_speed_group, 0);
    lv_obj_set_y(ui_Charging_speed_group, -25);
    lv_obj_set_align(ui_Charging_speed_group, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_radius(ui_Charging_speed_group, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Charging_speed_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Charging_speed_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Charging_speed_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Charging_speed_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Speed_label = lv_label_create(ui_Charging_speed_group);
    lv_obj_set_width(ui_Speed_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Speed_label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Speed_label, "Current charging speed");
    lv_obj_set_style_text_color(ui_Speed_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speed_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Speed_label, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Speed_group = lv_obj_create(ui_Charging_speed_group);
    lv_obj_set_width(ui_Speed_group, LV_SIZE_CONTENT);   /// 21
    lv_obj_set_height(ui_Speed_group, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Speed_group, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Speed_group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Speed_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Speed_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Speed_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Speed_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Speed_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Speed_group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Num_label3 = lv_label_create(ui_Speed_group);
    lv_obj_set_width(ui_Num_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Num_label3, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_align(ui_Num_label3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Num_label3, "210");
    lv_obj_set_style_text_color(ui_Num_label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Num_label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Num_label3, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Kw_ = lv_label_create(ui_Speed_group);
    lv_obj_set_height(ui_Kw_, 25);
    lv_obj_set_width(ui_Kw_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Kw_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Kw_, "kW");
    lv_obj_set_style_text_color(ui_Kw_, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Kw_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Kw_, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Whitespace_ghostbtn = lv_obj_create(ui_Cardbg_ghostbtn);
    lv_obj_remove_style_all(ui_Whitespace_ghostbtn);
    lv_obj_set_width(ui_Whitespace_ghostbtn, 225);
    lv_obj_set_height(ui_Whitespace_ghostbtn, 40);
    lv_obj_set_align(ui_Whitespace_ghostbtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Whitespace_ghostbtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Stop_button = ui_button_create(ui_Charging);
    lv_obj_set_width(ui_Stop_button, 200);
    lv_obj_set_height(ui_Stop_button, 40);
    lv_obj_set_x(ui_Stop_button, -25);
    lv_obj_set_y(ui_Stop_button, -25);
    lv_obj_set_align(ui_Stop_button, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_style_bg_color(ui_Stop_button, lv_color_hex(0xDB2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Stop_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Stop_button, lv_color_hex(0xDB2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Stop_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Stop_button, lv_color_hex(0xD40000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Stop_button, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_label_set_text(ui_comp_get_child(ui_Stop_button, UI_COMP_BUTTON_BUTTON_LABEL), "Stop Charging");

    lv_obj_add_event_cb(ui_Stop_button, ui_event_Stop_button_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Charging, ui_event_Charging, LV_EVENT_ALL, NULL);

}
