// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "ui.h"

void ui_End_screen_init(void)
{
    ui_End = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_End, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_End, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_End, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_End, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_End, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_bg_img7 = lv_img_create(ui_End);
    lv_img_set_src(ui_Main_bg_img7, &ui_img_bg4_png);
    lv_obj_set_width(ui_Main_bg_img7, LV_SIZE_CONTENT);   /// 640
    lv_obj_set_height(ui_Main_bg_img7, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_align(ui_Main_bg_img7, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Main_bg_img7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Main_bg_img7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Full_content4 = lv_obj_create(ui_End);
    lv_obj_set_width(ui_Full_content4, lv_pct(100));
    lv_obj_set_height(ui_Full_content4, lv_pct(100));
    lv_obj_set_align(ui_Full_content4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Full_content4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Full_content4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Full_content4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_content4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_content4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Full_content4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Full_content4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Full_content4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Full_content4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_group7 = lv_obj_create(ui_Full_content4);
    lv_obj_remove_style_all(ui_Statusbar_group7);
    lv_obj_set_height(ui_Statusbar_group7, 31);
    lv_obj_set_width(ui_Statusbar_group7, lv_pct(100));
    lv_obj_set_align(ui_Statusbar_group7, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Statusbar_group7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Statusbar_group7, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Statusbar_group7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Statusbar_group7, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Statusbar_group7, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Statusbar_group7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Statusbar_group7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_info6 = lv_obj_create(ui_Statusbar_group7);
    lv_obj_set_width(ui_Statusbar_info6, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Statusbar_info6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_Statusbar_info6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Statusbar_info6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Statusbar_info6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Statusbar_info6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Statusbar_info6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Statusbar_info6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Statusbar_info6, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Contact_icon7 = lv_img_create(ui_Statusbar_info6);
    lv_img_set_src(ui_Contact_icon7, &ui_img_contact_png);
    lv_obj_set_width(ui_Contact_icon7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Contact_icon7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Contact_icon7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Contact_icon7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Contact_icon7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Call_number1 = lv_label_create(ui_Statusbar_info6);
    lv_obj_set_width(ui_Call_number1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Call_number1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Call_number1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Call_number1, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_Call_number1, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Call_number1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Call_number1, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_date1 = lv_label_create(ui_Statusbar_group7);
    lv_obj_set_width(ui_Statusbar_date1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Statusbar_date1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Statusbar_date1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Statusbar_date1, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_Statusbar_date1, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Statusbar_date1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Statusbar_date1, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Statusbar_date1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Statusbar_date1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Statusbar_date1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Statusbar_date1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Two_columns = lv_obj_create(ui_Full_content4);
    lv_obj_remove_style_all(ui_Two_columns);
    lv_obj_set_width(ui_Two_columns, lv_pct(100));
    lv_obj_set_flex_grow(ui_Two_columns, 1);
    lv_obj_set_align(ui_Two_columns, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Two_columns, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Two_columns, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Two_columns, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Two_columns, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Two_columns, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Two_columns, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Two_columns, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Two_columns, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Two_columns, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart_animcontainer = lv_obj_create(ui_Two_columns);
    lv_obj_remove_style_all(ui_Chart_animcontainer);
    lv_obj_set_height(ui_Chart_animcontainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_Chart_animcontainer, 1);
    lv_obj_set_align(ui_Chart_animcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Chart_animcontainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Full_chart_group = lv_obj_create(ui_Chart_animcontainer);
    lv_obj_set_width(ui_Full_chart_group, lv_pct(100));
    lv_obj_set_height(ui_Full_chart_group, lv_pct(100));
    lv_obj_set_flex_flow(ui_Full_chart_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Full_chart_group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Full_chart_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_chart_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_chart_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Full_chart_group, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Full_chart_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Full_chart_group, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Full_chart_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Full_chart_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Full_chart_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart = lv_chart_create(ui_Full_chart_group);
    lv_obj_set_width(ui_Chart, lv_pct(100));
    lv_obj_set_flex_grow(ui_Chart, 1);
    lv_obj_set_align(ui_Chart, LV_ALIGN_TOP_MID);
    lv_chart_set_type(ui_Chart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart, 22);
    lv_chart_set_range(ui_Chart, LV_CHART_AXIS_PRIMARY_Y, 1, 100);
    lv_chart_set_div_line_count(ui_Chart, 10, 22);
    lv_chart_set_zoom_x(ui_Chart, 600);
    lv_chart_set_zoom_y(ui_Chart, 256);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 54, 1, true, 50);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 5, 2, false, 25);
    lv_chart_series_t * ui_Chart_series_1 = lv_chart_add_series(ui_Chart, lv_color_hex(0x3BB7FC), LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart_series_1_array[] = { 3, 12, 20, 28, 36, 44, 48, 52, 57, 60, 64, 68, 70, 72, 75, 78, 80, 81, 82, 83, 84, 85 };
    lv_chart_set_ext_y_array(ui_Chart, ui_Chart_series_1, ui_Chart_series_1_array);
    lv_obj_set_style_radius(ui_Chart, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Chart, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Chart, lv_color_hex(0x100F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Chart, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Chart, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chart, lv_color_hex(0x22223D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chart, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Chart, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Chart, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_Chart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Chart, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Chart, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Chart, true, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chart, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chart, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Chart, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Chart, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Chart, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Chart, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_Chart, 4, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_Chart, true, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Chart, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Chart, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Chart, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Chart, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Chart, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Chart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_Chart, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart, lv_color_hex(0x100F1F), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart, lv_color_hex(0x19182D), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Total_label = lv_label_create(ui_Full_chart_group);
    lv_obj_set_width(ui_Total_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Total_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Total_label, 26);
    lv_obj_set_y(ui_Total_label, 26);
    lv_label_set_text(ui_Total_label, "Total energy delivered (kWh)");
    lv_obj_add_flag(ui_Total_label, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_Total_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Total_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Total_label, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time_label = lv_label_create(ui_Full_chart_group);
    lv_obj_set_width(ui_Time_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_label, lv_pct(9));
    lv_obj_set_y(ui_Time_label, lv_pct(35));
    lv_obj_set_align(ui_Time_label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Time_label, "Time (min)");
    lv_obj_set_style_text_color(ui_Time_label, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time_label, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg_and_sum_ = lv_obj_create(ui_Two_columns);
    lv_obj_remove_style_all(ui_Cardbg_and_sum_);
    lv_obj_set_width(ui_Cardbg_and_sum_, 298);
    lv_obj_set_height(ui_Cardbg_and_sum_, lv_pct(100));
    lv_obj_set_align(ui_Cardbg_and_sum_, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Cardbg_and_sum_, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Cardbg_and_sum_, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Cardbg_and_sum_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Cardbg_and_sum_, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_and_sum_, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_and_sum_, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_and_sum_, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Cardbg_and_sum_, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Cardbg_and_sum_, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg_animcontainer8 = lv_obj_create(ui_Cardbg_and_sum_);
    lv_obj_remove_style_all(ui_Cardbg_animcontainer8);
    lv_obj_set_width(ui_Cardbg_animcontainer8, lv_pct(100));
    lv_obj_set_flex_grow(ui_Cardbg_animcontainer8, 2);
    lv_obj_set_align(ui_Cardbg_animcontainer8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Cardbg_animcontainer8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Cardbg_animcontainer8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_animcontainer8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_animcontainer8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_animcontainer8, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg7 = ui_cardbg_create(ui_Cardbg_animcontainer8);
    lv_obj_set_width(ui_Cardbg7, lv_pct(100));
    lv_obj_set_height(ui_Cardbg7, lv_pct(100));
    lv_obj_set_y(ui_Cardbg7, 0);
    lv_obj_set_x(ui_Cardbg7, lv_pct(0));
    lv_obj_set_align(ui_Cardbg7, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Cardbg7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Cardbg7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Cardbg7, LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    lv_obj_set_style_pad_left(ui_Cardbg7, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg7, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg7, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg7, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Fee_group = lv_obj_create(ui_Cardbg7);
    lv_obj_set_width(ui_Fee_group, lv_pct(100));
    lv_obj_set_height(ui_Fee_group, LV_SIZE_CONTENT);    /// 130
    lv_obj_set_flex_flow(ui_Fee_group, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Fee_group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Fee_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Fee_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fee_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Total_label2 = lv_label_create(ui_Fee_group);
    lv_obj_set_width(ui_Total_label2, lv_pct(100));
    lv_obj_set_height(ui_Total_label2, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Total_label2, "Total energy delivered");
    lv_obj_set_style_text_color(ui_Total_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Total_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Total_label2, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Num_label4 = lv_label_create(ui_Fee_group);
    lv_obj_set_width(ui_Num_label4, lv_pct(100));
    lv_obj_set_height(ui_Num_label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Num_label4, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Num_label4, "87 kWh");
    lv_obj_set_style_text_color(ui_Num_label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Num_label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Num_label4, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fee_group2 = lv_obj_create(ui_Cardbg7);
    lv_obj_set_width(ui_Fee_group2, lv_pct(100));
    lv_obj_set_height(ui_Fee_group2, LV_SIZE_CONTENT);    /// 130
    lv_obj_set_align(ui_Fee_group2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_Fee_group2, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Fee_group2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Fee_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Fee_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fee_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time_label2 = lv_label_create(ui_Fee_group2);
    lv_obj_set_width(ui_Time_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time_label2, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Time_label2, "Charging time");
    lv_obj_set_style_text_color(ui_Time_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time_label2, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Num_label5 = lv_label_create(ui_Fee_group2);
    lv_obj_set_width(ui_Num_label5, lv_pct(100));
    lv_obj_set_height(ui_Num_label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Num_label5, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Num_label5, "53 min");
    lv_obj_set_style_text_color(ui_Num_label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Num_label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Num_label5, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sum_container = lv_obj_create(ui_Cardbg_and_sum_);
    lv_obj_remove_style_all(ui_Sum_container);
    lv_obj_set_width(ui_Sum_container, lv_pct(82));
    lv_obj_set_flex_grow(ui_Sum_container, 1);
    lv_obj_set_align(ui_Sum_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Sum_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Sum_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Sum_container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Sum_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Sum_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Summary_price = lv_label_create(ui_Sum_container);
    lv_obj_set_width(ui_Summary_price, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Summary_price, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_Summary_price, 0);
    lv_obj_set_y(ui_Summary_price, 20);
    lv_obj_set_align(ui_Summary_price, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Summary_price, "$118");
    lv_obj_add_flag(ui_Summary_price, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_Summary_price, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Summary_price, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Summary_price, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Summary_price, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Summary_price, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Summary_price, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Summary_price, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Total_cost = lv_label_create(ui_Sum_container);
    lv_obj_set_width(ui_Total_cost, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Total_cost, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Total_cost, 44);
    lv_obj_set_y(ui_Total_cost, -27);
    lv_obj_set_align(ui_Total_cost, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Total_cost, "Total session cost");
    lv_obj_add_flag(ui_Total_cost, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_Total_cost, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Total_cost, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Total_cost, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Whitespace2 = lv_obj_create(ui_Full_content4);
    lv_obj_remove_style_all(ui_Whitespace2);
    lv_obj_set_width(ui_Whitespace2, 100);
    lv_obj_set_height(ui_Whitespace2, lv_pct(3));
    lv_obj_set_align(ui_Whitespace2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Whitespace2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Space_container = lv_obj_create(ui_Full_content4);
    lv_obj_remove_style_all(ui_Space_container);
    lv_obj_set_height(ui_Space_container, 65);
    lv_obj_set_width(ui_Space_container, lv_pct(100));
    lv_obj_set_align(ui_Space_container, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Space_container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Finish_button = ui_button_create(ui_End);
    lv_obj_set_x(ui_Finish_button, -25);
    lv_obj_set_y(ui_Finish_button, -25);
    lv_obj_set_align(ui_Finish_button, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_style_bg_color(ui_Finish_button, lv_color_hex(0x01D358), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Finish_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Finish_button, lv_color_hex(0x01D358), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Finish_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Finish_button, lv_color_hex(0x00B74B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Finish_button, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_label_set_text(ui_comp_get_child(ui_Finish_button, UI_COMP_BUTTON_BUTTON_LABEL), "Finish");

    ui_Cardbg_ghostbtn2 = lv_obj_create(ui_End);
    lv_obj_remove_style_all(ui_Cardbg_ghostbtn2);
    lv_obj_set_height(ui_Cardbg_ghostbtn2, 65);
    lv_obj_set_width(ui_Cardbg_ghostbtn2, lv_pct(100));
    lv_obj_set_align(ui_Cardbg_ghostbtn2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_Cardbg_ghostbtn2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Cardbg_ghostbtn2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Cardbg_ghostbtn2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Cardbg_ghostbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_ghostbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_ghostbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_ghostbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Cardbg_ghostbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Cardbg_ghostbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg_animcontainer9 = lv_obj_create(ui_Cardbg_ghostbtn2);
    lv_obj_remove_style_all(ui_Cardbg_animcontainer9);
    lv_obj_set_height(ui_Cardbg_animcontainer9, 65);
    lv_obj_set_flex_grow(ui_Cardbg_animcontainer9, 1);
    lv_obj_set_align(ui_Cardbg_animcontainer9, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Cardbg_animcontainer9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Cardbg_animcontainer9, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_animcontainer9, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_animcontainer9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_animcontainer9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg1 = ui_cardbg_create(ui_Cardbg_animcontainer9);
    lv_obj_set_height(ui_Cardbg1, 40);
    lv_obj_set_width(ui_Cardbg1, lv_pct(100));
    lv_obj_set_x(ui_Cardbg1, 0);
    lv_obj_set_y(ui_Cardbg1, -25);
    lv_obj_set_align(ui_Cardbg1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_radius(ui_Cardbg1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Cardbg1, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charge_bar = lv_obj_create(ui_Cardbg1);
    lv_obj_set_height(ui_Charge_bar, 40);
    lv_obj_set_width(ui_Charge_bar, lv_pct(100));
    lv_obj_set_flex_flow(ui_Charge_bar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Charge_bar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Charge_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Charge_bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Charge_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Green_panel = lv_obj_create(ui_Charge_bar);
    lv_obj_set_height(ui_Green_panel, 30);
    lv_obj_set_width(ui_Green_panel, lv_pct(15));
    lv_obj_set_align(ui_Green_panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Green_panel, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_Green_panel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Green_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Green_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Green_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Green_panel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Green_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Green_startbar2 = lv_obj_create(ui_Green_panel);
    lv_obj_set_height(ui_Green_startbar2, 30);
    lv_obj_set_width(ui_Green_startbar2, lv_pct(100));
    lv_obj_clear_flag(ui_Green_startbar2, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Green_startbar2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Green_startbar2, lv_color_hex(0x00B94C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Green_startbar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Green_startbar2, lv_color_hex(0x05FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Green_startbar2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Green_startbar2, lv_color_hex(0x05FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Green_startbar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Green_startbar2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blue_panel = lv_obj_create(ui_Charge_bar);
    lv_obj_set_height(ui_Blue_panel, 30);
    lv_obj_set_width(ui_Blue_panel, lv_pct(65));
    lv_obj_set_align(ui_Blue_panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Blue_panel, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_Blue_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Blue_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Blue_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Blue_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Blue_panel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Blue_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blue_indicator1 = lv_obj_create(ui_Blue_panel);
    lv_obj_set_height(ui_Blue_indicator1, 30);
    lv_obj_set_width(ui_Blue_indicator1, lv_pct(100));
    lv_obj_set_x(ui_Blue_indicator1, -355);
    lv_obj_set_y(ui_Blue_indicator1, 12);
    lv_obj_set_align(ui_Blue_indicator1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Blue_indicator1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Blue_indicator1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Blue_indicator1, lv_color_hex(0x0067D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Blue_indicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Blue_indicator1, lv_color_hex(0x3FBDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Blue_indicator1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Blue_indicator1, lv_color_hex(0x3FCFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Blue_indicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Blue_indicator1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Space_panel = lv_obj_create(ui_Charge_bar);
    lv_obj_set_height(ui_Space_panel, 30);
    lv_obj_set_flex_grow(ui_Space_panel, 1);
    lv_obj_set_align(ui_Space_panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Space_panel, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_Space_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Space_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Space_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Space_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Space_panel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Space_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Space_bar = lv_obj_create(ui_Space_panel);
    lv_obj_set_height(ui_Space_bar, 30);
    lv_obj_set_width(ui_Space_bar, lv_pct(61));
    lv_obj_set_align(ui_Space_bar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Space_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Space_bar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Space_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ghostbutton = lv_obj_create(ui_Cardbg_ghostbtn2);
    lv_obj_remove_style_all(ui_Ghostbutton);
    lv_obj_set_width(ui_Ghostbutton, 225);
    lv_obj_set_height(ui_Ghostbutton, 40);
    lv_obj_set_align(ui_Ghostbutton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Ghostbutton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Finish_button, ui_event_Finish_button_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_End, ui_event_End, LV_EVENT_ALL, NULL);

}
