// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "ui.h"

void ui_Help_screen_init(void)
{
    ui_Help = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Help, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Help, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Help, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_group2 = lv_obj_create(ui_Help);
    lv_obj_set_width(ui_Main_group2, lv_pct(100));
    lv_obj_set_height(ui_Main_group2, lv_pct(100));
    lv_obj_set_align(ui_Main_group2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_group2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Main_group2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Main_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Full_content6 = lv_obj_create(ui_Main_group2);
    lv_obj_set_height(ui_Full_content6, lv_pct(100));
    lv_obj_set_flex_grow(ui_Full_content6, 1);
    lv_obj_set_align(ui_Full_content6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Full_content6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_content6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_content6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Full_content6, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Full_content6, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Full_content6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Full_content6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_bg_img9 = lv_img_create(ui_Full_content6);
    lv_img_set_src(ui_Main_bg_img9, &ui_img_bg4_png);
    lv_obj_set_width(ui_Main_bg_img9, LV_SIZE_CONTENT);   /// 640
    lv_obj_set_height(ui_Main_bg_img9, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_x(ui_Main_bg_img9, 0);
    lv_obj_set_y(ui_Main_bg_img9, -10);
    lv_obj_set_align(ui_Main_bg_img9, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Main_bg_img9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Main_bg_img9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Statusbar_group8 = lv_obj_create(ui_Full_content6);
    lv_obj_set_width(ui_Statusbar_group8, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Statusbar_group8, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_Statusbar_group8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Statusbar_group8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Statusbar_group8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Statusbar_group8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Statusbar_group8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Statusbar_group8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Statusbar_group8, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Contact_icon8 = lv_img_create(ui_Statusbar_group8);
    lv_img_set_src(ui_Contact_icon8, &ui_img_contact_png);
    lv_obj_set_width(ui_Contact_icon8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Contact_icon8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Contact_icon8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Contact_icon8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Contact_icon8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Call_number8 = lv_label_create(ui_Statusbar_group8);
    lv_obj_set_width(ui_Call_number8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Call_number8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Call_number8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Call_number8, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_Call_number8, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Call_number8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Call_number8, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_date8 = lv_label_create(ui_Full_content6);
    lv_obj_set_width(ui_Statusbar_date8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Statusbar_date8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Statusbar_date8, 0);
    lv_obj_set_y(ui_Statusbar_date8, 1);
    lv_obj_set_align(ui_Statusbar_date8, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Statusbar_date8, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_Statusbar_date8, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Statusbar_date8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Statusbar_date8, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_button8 = ui_button_create(ui_Full_content6);
    lv_obj_set_x(ui_Back_button8, 0);
    lv_obj_set_y(ui_Back_button8, -25);
    lv_obj_set_align(ui_Back_button8, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_Back_button8, UI_COMP_BUTTON_BUTTON_LABEL), "Back");

    ui_Cardbg_animcontainer11 = lv_obj_create(ui_Help);
    lv_obj_set_width(ui_Cardbg_animcontainer11, lv_pct(70));
    lv_obj_set_height(ui_Cardbg_animcontainer11, lv_pct(88));
    lv_obj_set_align(ui_Cardbg_animcontainer11, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Cardbg_animcontainer11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Cardbg_animcontainer11, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cardbg_animcontainer11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Cardbg_animcontainer11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_animcontainer11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_animcontainer11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_animcontainer11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg13 = lv_obj_create(ui_Cardbg_animcontainer11);
    lv_obj_set_width(ui_Cardbg13, lv_pct(88));
    lv_obj_set_height(ui_Cardbg13, lv_pct(88));
    lv_obj_set_align(ui_Cardbg13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Cardbg13, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Cardbg13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_Cardbg13, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Cardbg13, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cardbg13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Cardbg13, lv_color_hex(0x0F0E1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Cardbg13, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Cardbg13, lv_color_hex(0x0F0E1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Cardbg13, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Cardbg13, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Cardbg13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Cardbg13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Cardbg13, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Cardbg13, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg13, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg13, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg13, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Cardbg13, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Cardbg13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Cardbg13, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg13, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg13, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg13, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Created_title_ = lv_obj_create(ui_Cardbg13);
    lv_obj_remove_style_all(ui_Created_title_);
    lv_obj_set_width(ui_Created_title_, lv_pct(100));
    lv_obj_set_height(ui_Created_title_, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Created_title_, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Created_title_, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Created_title_, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Created_title_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Createdby = lv_label_create(ui_Created_title_);
    lv_obj_set_width(ui_Createdby, lv_pct(100));
    lv_obj_set_height(ui_Createdby, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Createdby, "This demo created by");
    lv_obj_set_style_text_color(ui_Createdby, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Createdby, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Createdby, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLS1 = lv_label_create(ui_Created_title_);
    lv_obj_set_width(ui_SLS1, lv_pct(100));
    lv_obj_set_height(ui_SLS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SLS1, 0);
    lv_obj_set_y(ui_SLS1, 69);
    lv_label_set_text(ui_SLS1, "SquareLine Studio");
    lv_obj_set_style_text_color(ui_SLS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SLS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SLS1, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLS1_extract = lv_obj_create(ui_Cardbg13);
    lv_obj_remove_style_all(ui_SLS1_extract);
    lv_obj_set_width(ui_SLS1_extract, lv_pct(100));
    lv_obj_set_height(ui_SLS1_extract, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SLS1_extract, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SLS1_extract, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SLS1_extract, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SLS1_extract, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_SLS1_extract, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SLS1_extract, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_About_sls1 = lv_label_create(ui_SLS1_extract);
    lv_obj_set_width(ui_About_sls1, lv_pct(100));
    lv_obj_set_height(ui_About_sls1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_About_sls1, 2);
    lv_obj_set_y(ui_About_sls1, 46);
    lv_label_set_text(ui_About_sls1,
                      "Next generation UI editor for individuals and professionals to design and develop beautiful UIs for your embedded devices quickly and easily.");
    lv_obj_set_style_text_color(ui_About_sls1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_About_sls1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_About_sls1, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLS1_offers = lv_label_create(ui_SLS1_extract);
    lv_obj_set_width(ui_SLS1_offers, lv_pct(100));
    lv_obj_set_height(ui_SLS1_offers, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLS1_offers, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_SLS1_offers,
                      "SquareLine Studio offers flexible licenses for all use cases, including personal use, startups, and large companies as well.");
    lv_obj_set_style_text_color(ui_SLS1_offers, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SLS1_offers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SLS1_offers, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Authentication = lv_label_create(ui_SLS1_extract);
    lv_obj_set_width(ui_Authentication, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Authentication, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Authentication, 0);
    lv_obj_set_y(ui_Authentication, 99);
    lv_label_set_text(ui_Authentication, "Authentication");
    lv_obj_add_flag(ui_Authentication, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Authentication, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Authentication, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Authentication, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LVGL_extract = lv_obj_create(ui_Cardbg13);
    lv_obj_remove_style_all(ui_LVGL_extract);
    lv_obj_set_width(ui_LVGL_extract, lv_pct(100));
    lv_obj_set_height(ui_LVGL_extract, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_LVGL_extract, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LVGL_extract, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_LVGL_extract, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_LVGL_extract, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_LVGL_extract, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_LVGL_extract, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Poweredby = lv_label_create(ui_LVGL_extract);
    lv_obj_set_width(ui_Poweredby, lv_pct(100));
    lv_obj_set_height(ui_Poweredby, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Poweredby, 0);
    lv_obj_set_y(ui_Poweredby, -141);
    lv_obj_set_align(ui_Poweredby, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Poweredby, "Powered by LVGL");
    lv_obj_set_style_text_color(ui_Poweredby, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Poweredby, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Poweredby, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_About_lvgl = lv_label_create(ui_LVGL_extract);
    lv_obj_set_width(ui_About_lvgl, lv_pct(100));
    lv_obj_set_height(ui_About_lvgl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_About_lvgl, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_About_lvgl,
                      "Under the hood SquareLine Studio uses the amazing LVGL GUI library. LVGL is the most popular free and open-source embedded graphics library to create beautiful UIs for any MCU, MPU and display type.");
    lv_obj_set_style_text_color(ui_About_lvgl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_About_lvgl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_About_lvgl, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Qr_container_ = lv_obj_create(ui_Help);
    lv_obj_remove_style_all(ui_Qr_container_);
    lv_obj_set_width(ui_Qr_container_, 300);
    lv_obj_set_height(ui_Qr_container_, lv_pct(100));
    lv_obj_set_align(ui_Qr_container_, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Qr_container_, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Qr2 = lv_img_create(ui_Qr_container_);
    lv_img_set_src(ui_Qr2, &ui_img_qr_code2_png);
    lv_obj_set_width(ui_Qr2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Qr2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Qr2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Qr2, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Qr2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Back_button8, ui_event_Back_button8_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Help, ui_event_Help, LV_EVENT_ALL, NULL);

}
