// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Full_content_group = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_Full_content_group, lv_pct(100));
    lv_obj_set_height(ui_Full_content_group, lv_pct(100));
    lv_obj_set_align(ui_Full_content_group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Full_content_group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Full_content_group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Full_content_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_content_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_content_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slidebar = lv_obj_create(ui_Full_content_group);
    lv_obj_set_width(ui_Slidebar, 64);
    lv_obj_set_height(ui_Slidebar, lv_pct(100));
    lv_obj_set_align(ui_Slidebar, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Slidebar, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Slidebar, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slidebar, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Slidebar, lv_color_hex(0x115AE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slidebar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Slidebar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Slidebar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slidebar_bg = lv_img_create(ui_Slidebar);
    lv_img_set_src(ui_Slidebar_bg, &ui_img_left_side_png);
    lv_obj_set_width(ui_Slidebar_bg, LV_SIZE_CONTENT);   /// 66
    lv_obj_set_height(ui_Slidebar_bg, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_align(ui_Slidebar_bg, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Slidebar_bg, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Slidebar_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pricing_group = lv_obj_create(ui_Slidebar);
    lv_obj_set_width(ui_Pricing_group, 60);
    lv_obj_set_height(ui_Pricing_group, 60);
    lv_obj_set_align(ui_Pricing_group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Pricing_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Pricing_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Pricing_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pricing_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pricing_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Pricing_group, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Pricing_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Pricing_group, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Pricing_group, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Pricing_group, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Pricing_icon = lv_img_create(ui_Pricing_group);
    lv_img_set_src(ui_Pricing_icon, &ui_img_pricing_png);
    lv_obj_set_width(ui_Pricing_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pricing_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pricing_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pricing_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pricing_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pricing_label = lv_label_create(ui_Pricing_group);
    lv_obj_set_width(ui_Pricing_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pricing_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pricing_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pricing_label, "Pricing");
    lv_obj_set_style_text_color(ui_Pricing_label, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pricing_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pricing_label, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Help_group = lv_obj_create(ui_Slidebar);
    lv_obj_set_width(ui_Help_group, 60);
    lv_obj_set_height(ui_Help_group, 60);
    lv_obj_set_align(ui_Help_group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Help_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Help_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Help_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Help_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Help_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Help_group, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Help_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Help_group, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Help_group, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Help_group, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Help_icon = lv_img_create(ui_Help_group);
    lv_img_set_src(ui_Help_icon, &ui_img_help_png);
    lv_obj_set_width(ui_Help_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Help_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Help_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Help_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Help_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Help_label = lv_label_create(ui_Help_group);
    lv_obj_set_width(ui_Help_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Help_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Help_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Help_label, "Help");
    lv_obj_set_style_text_color(ui_Help_label, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Help_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Help_label, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Content_of_objects = lv_obj_create(ui_Full_content_group);
    lv_obj_set_height(ui_Content_of_objects, lv_pct(100));
    lv_obj_set_flex_grow(ui_Content_of_objects, 1);
    lv_obj_set_align(ui_Content_of_objects, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Content_of_objects, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Content_of_objects, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Content_of_objects, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Content_of_objects, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Content_of_objects, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Content_of_objects, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Content_of_objects, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_bg_img = lv_img_create(ui_Content_of_objects);
    lv_img_set_src(ui_Main_bg_img, &ui_img_bg4_png);
    lv_obj_set_width(ui_Main_bg_img, LV_SIZE_CONTENT);   /// 640
    lv_obj_set_height(ui_Main_bg_img, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_x(ui_Main_bg_img, 0);
    lv_obj_set_y(ui_Main_bg_img, -10);
    lv_obj_set_align(ui_Main_bg_img, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Main_bg_img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Main_bg_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Statusbar_group = lv_obj_create(ui_Content_of_objects);
    lv_obj_set_width(ui_Statusbar_group, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Statusbar_group, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_Statusbar_group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Statusbar_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Statusbar_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Statusbar_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Statusbar_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Statusbar_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Statusbar_group, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Contact_icon = lv_img_create(ui_Statusbar_group);
    lv_img_set_src(ui_Contact_icon, &ui_img_contact_png);
    lv_obj_set_width(ui_Contact_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Contact_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Contact_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Contact_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Contact_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Call_number = lv_label_create(ui_Statusbar_group);
    lv_obj_set_width(ui_Call_number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Call_number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Call_number, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Call_number, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_Call_number, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Call_number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Call_number, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_date = lv_label_create(ui_Content_of_objects);
    lv_obj_set_width(ui_Statusbar_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Statusbar_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Statusbar_date, 0);
    lv_obj_set_y(ui_Statusbar_date, 1);
    lv_obj_set_align(ui_Statusbar_date, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Statusbar_date, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_Statusbar_date, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Statusbar_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Statusbar_date, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bottom_charger_id = lv_label_create(ui_Content_of_objects);
    lv_obj_set_width(ui_Bottom_charger_id, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bottom_charger_id, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bottom_charger_id, 0);
    lv_obj_set_y(ui_Bottom_charger_id, -10);
    lv_obj_set_align(ui_Bottom_charger_id, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Bottom_charger_id, "Charger #5879965-08");
    lv_obj_set_style_text_color(ui_Bottom_charger_id, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Bottom_charger_id, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Bottom_charger_id, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg_animcontainer = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_Cardbg_animcontainer, lv_pct(61));
    lv_obj_set_height(ui_Cardbg_animcontainer, lv_pct(77));
    lv_obj_clear_flag(ui_Cardbg_animcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Cardbg_animcontainer, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cardbg_animcontainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg = ui_cardbg_create(ui_Cardbg_animcontainer);
    lv_obj_set_width(ui_Cardbg, lv_pct(88));
    lv_obj_set_height(ui_Cardbg, lv_pct(72));
    lv_obj_set_x(ui_Cardbg, 0);
    lv_obj_set_y(ui_Cardbg, 0);

    ui_Welcome_title = lv_label_create(ui_Cardbg);
    lv_obj_set_width(ui_Welcome_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Welcome_title, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Welcome_title, "Welcome!");
    lv_obj_set_style_text_color(ui_Welcome_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Welcome_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Welcome_title, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charger_extract = lv_label_create(ui_Cardbg);
    lv_obj_set_width(ui_Charger_extract, lv_pct(100));
    lv_obj_set_height(ui_Charger_extract, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Charger_extract, 2);
    lv_obj_set_y(ui_Charger_extract, 46);
    lv_label_set_text(ui_Charger_extract, "The world's fastest and best charger is at your disposal.");
    lv_obj_set_style_text_color(ui_Charger_extract, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Charger_extract, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Charger_extract, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Started_h1 = lv_label_create(ui_Cardbg);
    lv_obj_set_width(ui_Started_h1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Started_h1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Started_h1, 0);
    lv_obj_set_y(ui_Started_h1, 96);
    lv_label_set_text(ui_Started_h1, "Get started!");
    lv_obj_set_style_text_color(ui_Started_h1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Started_h1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Started_h1, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_carimg = lv_img_create(ui_Home);
    lv_img_set_src(ui_carimg, &ui_img_s1_car_png);
    lv_obj_set_width(ui_carimg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_carimg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_carimg, 53);
    lv_obj_set_y(ui_carimg, 73);
    lv_obj_set_align(ui_carimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_carimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_carimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Start_button = ui_button_create(ui_Home);
    lv_obj_set_x(ui_Start_button, -25);
    lv_obj_set_y(ui_Start_button, -25);
    lv_obj_set_align(ui_Start_button, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_Start_button, UI_COMP_BUTTON_BUTTON_LABEL), "Start Charging");

    lv_obj_add_event_cb(ui_Pricing_group, ui_event_Pricing_group, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Help_group, ui_event_Help_group, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Start_button, ui_event_Start_button_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);

}
