// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "ui.h"

void ui_Pricing_screen_init(void)
{
    ui_Pricing = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Pricing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pricing, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pricing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_group = lv_obj_create(ui_Pricing);
    lv_obj_set_width(ui_Main_group, lv_pct(100));
    lv_obj_set_height(ui_Main_group, lv_pct(100));
    lv_obj_set_align(ui_Main_group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Main_group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Main_group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Main_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Full_content5 = lv_obj_create(ui_Main_group);
    lv_obj_set_height(ui_Full_content5, lv_pct(100));
    lv_obj_set_flex_grow(ui_Full_content5, 1);
    lv_obj_set_align(ui_Full_content5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Full_content5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_content5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_content5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Full_content5, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Full_content5, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Full_content5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Full_content5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_bg_img8 = lv_img_create(ui_Full_content5);
    lv_img_set_src(ui_Main_bg_img8, &ui_img_bg4_png);
    lv_obj_set_width(ui_Main_bg_img8, LV_SIZE_CONTENT);   /// 640
    lv_obj_set_height(ui_Main_bg_img8, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_x(ui_Main_bg_img8, 0);
    lv_obj_set_y(ui_Main_bg_img8, -10);
    lv_obj_set_align(ui_Main_bg_img8, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Main_bg_img8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Main_bg_img8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Statusbar_group4 = lv_obj_create(ui_Full_content5);
    lv_obj_set_width(ui_Statusbar_group4, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Statusbar_group4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_Statusbar_group4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Statusbar_group4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Statusbar_group4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Statusbar_group4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Statusbar_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Statusbar_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Statusbar_group4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Contact_icon4 = lv_img_create(ui_Statusbar_group4);
    lv_img_set_src(ui_Contact_icon4, &ui_img_contact_png);
    lv_obj_set_width(ui_Contact_icon4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Contact_icon4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Contact_icon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Contact_icon4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Contact_icon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Call_number7 = lv_label_create(ui_Statusbar_group4);
    lv_obj_set_width(ui_Call_number7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Call_number7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Call_number7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Call_number7, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_Call_number7, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Call_number7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Call_number7, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_date7 = lv_label_create(ui_Full_content5);
    lv_obj_set_width(ui_Statusbar_date7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Statusbar_date7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Statusbar_date7, 0);
    lv_obj_set_y(ui_Statusbar_date7, 1);
    lv_obj_set_align(ui_Statusbar_date7, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Statusbar_date7, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_Statusbar_date7, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Statusbar_date7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Statusbar_date7, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_button7 = ui_button_create(ui_Full_content5);
    lv_obj_set_x(ui_Back_button7, 0);
    lv_obj_set_y(ui_Back_button7, -25);
    lv_obj_set_align(ui_Back_button7, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_Back_button7, UI_COMP_BUTTON_BUTTON_LABEL), "Back");

    ui_Cardbg_animcontainer1 = lv_obj_create(ui_Pricing);
    lv_obj_set_width(ui_Cardbg_animcontainer1, lv_pct(70));
    lv_obj_set_height(ui_Cardbg_animcontainer1, lv_pct(88));
    lv_obj_set_align(ui_Cardbg_animcontainer1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Cardbg_animcontainer1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Cardbg_animcontainer1, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cardbg_animcontainer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Cardbg_animcontainer1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_animcontainer1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_animcontainer1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_animcontainer1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg11 = ui_cardbg_create(ui_Cardbg_animcontainer1);
    lv_obj_set_width(ui_Cardbg11, lv_pct(88));
    lv_obj_set_height(ui_Cardbg11, lv_pct(88));
    lv_obj_set_x(ui_Cardbg11, 0);
    lv_obj_set_y(ui_Cardbg11, 0);
    lv_obj_set_flex_flow(ui_Cardbg11, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Cardbg11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Cardbg11, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_pad_row(ui_Cardbg11, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Cardbg11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Cardbg11, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg11, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg11, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg11, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Welcoming = lv_obj_create(ui_Cardbg11);
    lv_obj_set_width(ui_Welcoming, lv_pct(100));
    lv_obj_set_height(ui_Welcoming, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Welcoming, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Welcoming, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Welcoming, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Welcoming, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Welcoming, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Welcoming, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Welcoming_label = lv_label_create(ui_Welcoming);
    lv_obj_set_width(ui_Welcoming_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Welcoming_label, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Welcoming_label, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Welcoming_label, "Welcome, Duven");
    lv_obj_set_style_text_color(ui_Welcoming_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Welcoming_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Welcoming_label, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Welcoming_text = lv_label_create(ui_Welcoming);
    lv_obj_set_width(ui_Welcoming_text, lv_pct(100));
    lv_obj_set_height(ui_Welcoming_text, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Welcoming_text,
                      "The first 30 minutes of fast charging are free. After 60 minutes you get 10% discount.");
    lv_obj_set_style_text_color(ui_Welcoming_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Welcoming_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Welcoming_text, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fee_panel2 = lv_obj_create(ui_Cardbg11);
    lv_obj_set_width(ui_Fee_panel2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Fee_panel2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Fee_panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Fee_panel2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Fee_panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Fee_panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Fee_panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fee_panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fee_label2 = lv_label_create(ui_Fee_panel2);
    lv_obj_set_width(ui_Fee_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fee_label2, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Fee_label2, "Session fee");
    lv_obj_set_style_text_color(ui_Fee_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Fee_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fee_label2, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Price_label2 = lv_label_create(ui_Fee_panel2);
    lv_obj_set_width(ui_Price_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Price_label2, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Price_label2, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Price_label2, "$0.00");
    lv_obj_set_style_text_color(ui_Price_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Price_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Price_label2, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_panel2 = lv_obj_create(ui_Cardbg11);
    lv_obj_set_width(ui_Charging_panel2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Charging_panel2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Charging_panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Charging_panel2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Charging_panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Charging_panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Charging_panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Charging_panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Num_label6 = lv_label_create(ui_Charging_panel2);
    lv_obj_set_width(ui_Num_label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Num_label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Num_label6, 0);
    lv_obj_set_y(ui_Num_label6, 1);
    lv_label_set_text(ui_Num_label6, "1-250 kW");
    lv_obj_set_style_text_color(ui_Num_label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Num_label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Num_label6, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Num_label7 = lv_label_create(ui_Charging_panel2);
    lv_obj_set_width(ui_Num_label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Num_label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Num_label7, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Num_label7, "$0.21/kWh");
    lv_obj_set_style_text_color(ui_Num_label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Num_label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Num_label7, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_panel3 = lv_obj_create(ui_Cardbg11);
    lv_obj_set_width(ui_Charging_panel3, lv_pct(100));
    lv_obj_set_height(ui_Charging_panel3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Charging_panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Charging_panel3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Charging_panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Charging_panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Charging_panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Charging_panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_speed2 = lv_label_create(ui_Charging_panel3);
    lv_obj_set_width(ui_Charging_speed2, lv_pct(100));
    lv_obj_set_height(ui_Charging_speed2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Charging_speed2, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Charging_speed2,
                      "The charging speed depends on the type of car\nand the capacity of the network.");
    lv_obj_set_style_text_color(ui_Charging_speed2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Charging_speed2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Charging_speed2, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pos_container = lv_obj_create(ui_Pricing);
    lv_obj_remove_style_all(ui_Pos_container);
    lv_obj_set_width(ui_Pos_container, 276);
    lv_obj_set_height(ui_Pos_container, lv_pct(100));
    lv_obj_set_align(ui_Pos_container, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Pos_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Pos_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Pos_container, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Pos_container, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Pos_container, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pos_img = lv_img_create(ui_Pos_container);
    lv_img_set_src(ui_Pos_img, &ui_img_pos_png);
    lv_obj_set_width(ui_Pos_img, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pos_img, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pos_img, 0);
    lv_obj_set_y(ui_Pos_img, -15);
    lv_obj_set_align(ui_Pos_img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pos_img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pos_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Back_button7, ui_event_Back_button7_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Pricing, ui_event_Pricing, LV_EVENT_ALL, NULL);

}
