// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "ui.h"

void ui_Step1_screen_init(void)
{
    ui_Step1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Step1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Step1, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Step1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Full_content2 = lv_obj_create(ui_Step1);
    lv_obj_set_width(ui_Full_content2, lv_pct(100));
    lv_obj_set_height(ui_Full_content2, lv_pct(100));
    lv_obj_set_align(ui_Full_content2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Full_content2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Full_content2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Full_content2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_content2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_content2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slidebar2 = lv_obj_create(ui_Full_content2);
    lv_obj_set_width(ui_Slidebar2, 64);
    lv_obj_set_height(ui_Slidebar2, lv_pct(100));
    lv_obj_set_align(ui_Slidebar2, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Slidebar2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Slidebar2, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slidebar2, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Slidebar2, lv_color_hex(0x115AE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slidebar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Slidebar2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Slidebar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slidebar_bg_ = lv_img_create(ui_Slidebar2);
    lv_img_set_src(ui_Slidebar_bg_, &ui_img_left_side_png);
    lv_obj_set_width(ui_Slidebar_bg_, LV_SIZE_CONTENT);   /// 66
    lv_obj_set_height(ui_Slidebar_bg_, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_align(ui_Slidebar_bg_, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Slidebar_bg_, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Slidebar_bg_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pricing_group2 = lv_obj_create(ui_Slidebar2);
    lv_obj_set_width(ui_Pricing_group2, 60);
    lv_obj_set_height(ui_Pricing_group2, 60);
    lv_obj_set_align(ui_Pricing_group2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Pricing_group2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Pricing_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Pricing_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pricing_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pricing_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Pricing_group2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Pricing_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Pricing_group2, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Pricing_group2, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Pricing_group2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Pricing_icon2 = lv_img_create(ui_Pricing_group2);
    lv_img_set_src(ui_Pricing_icon2, &ui_img_pricing_png);
    lv_obj_set_width(ui_Pricing_icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pricing_icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pricing_icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pricing_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pricing_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pricing_label2 = lv_label_create(ui_Pricing_group2);
    lv_obj_set_width(ui_Pricing_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pricing_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pricing_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pricing_label2, "Pricing");
    lv_obj_set_style_text_color(ui_Pricing_label2, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pricing_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pricing_label2, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Help_group2 = lv_obj_create(ui_Slidebar2);
    lv_obj_set_width(ui_Help_group2, 60);
    lv_obj_set_height(ui_Help_group2, 60);
    lv_obj_set_align(ui_Help_group2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Help_group2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Help_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Help_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Help_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Help_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Help_group2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Help_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Help_group2, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Help_group2, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Help_group2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Help_icon2 = lv_img_create(ui_Help_group2);
    lv_img_set_src(ui_Help_icon2, &ui_img_help_png);
    lv_obj_set_width(ui_Help_icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Help_icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Help_icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Help_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Help_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Help_label2 = lv_label_create(ui_Help_group2);
    lv_obj_set_width(ui_Help_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Help_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Help_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Help_label2, "Help");
    lv_obj_set_style_text_color(ui_Help_label2, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Help_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Help_label2, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Content_of_objects2 = lv_obj_create(ui_Full_content2);
    lv_obj_set_height(ui_Content_of_objects2, lv_pct(100));
    lv_obj_set_flex_grow(ui_Content_of_objects2, 1);
    lv_obj_set_align(ui_Content_of_objects2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Content_of_objects2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Content_of_objects2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Content_of_objects2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Content_of_objects2, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Content_of_objects2, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Content_of_objects2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Content_of_objects2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_bg_img2 = lv_img_create(ui_Content_of_objects2);
    lv_img_set_src(ui_Main_bg_img2, &ui_img_bg4_png);
    lv_obj_set_width(ui_Main_bg_img2, LV_SIZE_CONTENT);   /// 640
    lv_obj_set_height(ui_Main_bg_img2, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_x(ui_Main_bg_img2, -31);
    lv_obj_set_y(ui_Main_bg_img2, 0);
    lv_obj_set_align(ui_Main_bg_img2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_bg_img2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Main_bg_img2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Statusbar_group2 = lv_obj_create(ui_Content_of_objects2);
    lv_obj_set_width(ui_Statusbar_group2, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Statusbar_group2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_Statusbar_group2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Statusbar_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Statusbar_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Statusbar_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Statusbar_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Statusbar_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Statusbar_group2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Contact_icon2 = lv_img_create(ui_Statusbar_group2);
    lv_img_set_src(ui_Contact_icon2, &ui_img_contact_png);
    lv_obj_set_width(ui_Contact_icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Contact_icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Contact_icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Contact_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Contact_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Contact_icon2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Contact_icon2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Call_number2 = lv_label_create(ui_Statusbar_group2);
    lv_obj_set_width(ui_Call_number2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Call_number2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Call_number2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Call_number2, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_Call_number2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Call_number2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Call_number2, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_date2 = lv_label_create(ui_Content_of_objects2);
    lv_obj_set_width(ui_Statusbar_date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Statusbar_date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Statusbar_date2, 0);
    lv_obj_set_y(ui_Statusbar_date2, 1);
    lv_obj_set_align(ui_Statusbar_date2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Statusbar_date2, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_Statusbar_date2, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Statusbar_date2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Statusbar_date2, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg_animcontainer2 = lv_obj_create(ui_Step1);
    lv_obj_set_width(ui_Cardbg_animcontainer2, lv_pct(67));
    lv_obj_set_height(ui_Cardbg_animcontainer2, lv_pct(77));
    lv_obj_clear_flag(ui_Cardbg_animcontainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Cardbg_animcontainer2, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cardbg_animcontainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Cardbg_animcontainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_animcontainer2, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_animcontainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_animcontainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg2 = ui_cardbg_create(ui_Cardbg_animcontainer2);
    lv_obj_set_width(ui_Cardbg2, lv_pct(88));
    lv_obj_set_height(ui_Cardbg2, lv_pct(72));
    lv_obj_set_x(ui_Cardbg2, 0);
    lv_obj_set_y(ui_Cardbg2, 0);
    lv_obj_set_flex_flow(ui_Cardbg2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Cardbg2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(ui_Cardbg2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Cardbg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Step_labels = lv_obj_create(ui_Cardbg2);
    lv_obj_remove_style_all(ui_Step_labels);
    lv_obj_set_width(ui_Step_labels, lv_pct(100));
    lv_obj_set_height(ui_Step_labels, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Step_labels, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Step_labels, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Step_labels, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Step_labels, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Step_labels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Step_labels, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_One_icon = lv_label_create(ui_Step_labels);
    lv_obj_set_width(ui_One_icon, 50);
    lv_obj_set_height(ui_One_icon, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_One_icon, 5);
    lv_obj_set_y(ui_One_icon, 0);
    lv_label_set_text(ui_One_icon, "1");
    lv_obj_set_style_text_color(ui_One_icon, lv_color_hex(0x20203A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_One_icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_One_icon, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_One_icon, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_One_icon, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_One_icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_One_icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_One_icon, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_One_icon, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_One_icon, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_One_icon, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Step = lv_label_create(ui_Step_labels);
    lv_obj_set_width(ui_Step, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Step, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Step, 88);
    lv_obj_set_y(ui_Step, 0);
    lv_label_set_text(ui_Step, "Step");
    lv_obj_set_style_text_color(ui_Step, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Step, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Step, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Plugin_h2 = lv_label_create(ui_Cardbg2);
    lv_obj_set_width(ui_Plugin_h2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Plugin_h2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Plugin_h2, 0);
    lv_obj_set_y(ui_Plugin_h2, 99);
    lv_label_set_text(ui_Plugin_h2, "Plug in first");
    lv_obj_set_style_text_color(ui_Plugin_h2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Plugin_h2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Plugin_h2, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_First_step = lv_label_create(ui_Cardbg2);
    lv_obj_set_width(ui_First_step, lv_pct(100));
    lv_obj_set_height(ui_First_step, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_First_step, 0);
    lv_obj_set_y(ui_First_step, 241);
    lv_label_set_text(ui_First_step, "The first step is to plug the charger into the car's charging port.");
    lv_obj_set_style_text_color(ui_First_step, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_First_step, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_First_step, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plug = lv_img_create(ui_Step1);
    lv_img_set_src(ui_plug, &ui_img_plug_png);
    lv_obj_set_width(ui_plug, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plug, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plug, 173);
    lv_obj_set_y(ui_plug, 28);
    lv_obj_set_align(ui_plug, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_plug, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_plug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Next_button = ui_button_create(ui_Step1);
    lv_obj_set_x(ui_Next_button, -25);
    lv_obj_set_y(ui_Next_button, -25);
    lv_obj_set_align(ui_Next_button, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_Next_button, UI_COMP_BUTTON_BUTTON_LABEL), "Next Step");

    ui_Plagination = lv_obj_create(ui_Step1);
    lv_obj_remove_style_all(ui_Plagination);
    lv_obj_set_width(ui_Plagination, lv_pct(10));
    lv_obj_set_height(ui_Plagination, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Plagination, -235);
    lv_obj_set_y(ui_Plagination, -25);
    lv_obj_set_align(ui_Plagination, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Plagination, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_one_gray = lv_label_create(ui_Plagination);
    lv_obj_set_width(ui_one_gray, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_one_gray, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_one_gray, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_one_gray, "/2");
    lv_obj_set_style_text_color(ui_one_gray, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_one_gray, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_one_gray, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_two_black = lv_label_create(ui_Plagination);
    lv_obj_set_width(ui_two_black, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_two_black, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_two_black, -40);
    lv_obj_set_y(ui_two_black, 0);
    lv_obj_set_align(ui_two_black, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_two_black, "1");
    lv_obj_set_style_text_color(ui_two_black, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_two_black, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_two_black, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Pricing_group2, ui_event_Pricing_group2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Help_group2, ui_event_Help_group2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Next_button, ui_event_Next_button_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Step1, ui_event_Step1, LV_EVENT_ALL, NULL);

}
