// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "ui.h"

void ui_Step2_screen_init(void)
{
    ui_Step2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Step2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Step2, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Step2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Full_content3 = lv_obj_create(ui_Step2);
    lv_obj_set_width(ui_Full_content3, lv_pct(100));
    lv_obj_set_height(ui_Full_content3, lv_pct(100));
    lv_obj_set_align(ui_Full_content3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Full_content3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Full_content3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Full_content3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_content3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_content3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slidebar3 = lv_obj_create(ui_Full_content3);
    lv_obj_set_width(ui_Slidebar3, 64);
    lv_obj_set_height(ui_Slidebar3, lv_pct(100));
    lv_obj_set_align(ui_Slidebar3, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Slidebar3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Slidebar3, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slidebar3, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Slidebar3, lv_color_hex(0x115AE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slidebar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Slidebar3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Slidebar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slidebar_bg2 = lv_img_create(ui_Slidebar3);
    lv_img_set_src(ui_Slidebar_bg2, &ui_img_left_side_png);
    lv_obj_set_width(ui_Slidebar_bg2, LV_SIZE_CONTENT);   /// 66
    lv_obj_set_height(ui_Slidebar_bg2, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_align(ui_Slidebar_bg2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Slidebar_bg2, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Slidebar_bg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pricing_group3 = lv_obj_create(ui_Slidebar3);
    lv_obj_set_width(ui_Pricing_group3, 60);
    lv_obj_set_height(ui_Pricing_group3, 60);
    lv_obj_set_align(ui_Pricing_group3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Pricing_group3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Pricing_group3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Pricing_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pricing_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pricing_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Pricing_group3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Pricing_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Pricing_group3, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Pricing_group3, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Pricing_group3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Pricing_icon3 = lv_img_create(ui_Pricing_group3);
    lv_img_set_src(ui_Pricing_icon3, &ui_img_pricing_png);
    lv_obj_set_width(ui_Pricing_icon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pricing_icon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pricing_icon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pricing_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pricing_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pricing_label3 = lv_label_create(ui_Pricing_group3);
    lv_obj_set_width(ui_Pricing_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pricing_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pricing_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pricing_label3, "Pricing");
    lv_obj_set_style_text_color(ui_Pricing_label3, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pricing_label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pricing_label3, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_help_group3 = lv_obj_create(ui_Slidebar3);
    lv_obj_set_width(ui_help_group3, 60);
    lv_obj_set_height(ui_help_group3, 60);
    lv_obj_set_align(ui_help_group3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_help_group3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_help_group3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_help_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_help_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_help_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_help_group3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_help_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_help_group3, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_help_group3, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_help_group3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Help_icon3 = lv_img_create(ui_help_group3);
    lv_img_set_src(ui_Help_icon3, &ui_img_help_png);
    lv_obj_set_width(ui_Help_icon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Help_icon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Help_icon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Help_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Help_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Help_label3 = lv_label_create(ui_help_group3);
    lv_obj_set_width(ui_Help_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Help_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Help_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Help_label3, "Help");
    lv_obj_set_style_text_color(ui_Help_label3, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Help_label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Help_label3, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Content_of_objects3 = lv_obj_create(ui_Full_content3);
    lv_obj_set_height(ui_Content_of_objects3, lv_pct(100));
    lv_obj_set_flex_grow(ui_Content_of_objects3, 1);
    lv_obj_set_align(ui_Content_of_objects3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Content_of_objects3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Content_of_objects3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Content_of_objects3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Content_of_objects3, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Content_of_objects3, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Content_of_objects3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Content_of_objects3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_bg_img3 = lv_img_create(ui_Content_of_objects3);
    lv_img_set_src(ui_Main_bg_img3, &ui_img_bg4_png);
    lv_obj_set_width(ui_Main_bg_img3, LV_SIZE_CONTENT);   /// 640
    lv_obj_set_height(ui_Main_bg_img3, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_x(ui_Main_bg_img3, 0);
    lv_obj_set_y(ui_Main_bg_img3, -10);
    lv_obj_set_align(ui_Main_bg_img3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Main_bg_img3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Main_bg_img3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Statusbar_group3 = lv_obj_create(ui_Content_of_objects3);
    lv_obj_set_width(ui_Statusbar_group3, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Statusbar_group3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_Statusbar_group3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Statusbar_group3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Statusbar_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Statusbar_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Statusbar_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Statusbar_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Statusbar_group3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Contact_icon3 = lv_img_create(ui_Statusbar_group3);
    lv_img_set_src(ui_Contact_icon3, &ui_img_contact_png);
    lv_obj_set_width(ui_Contact_icon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Contact_icon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Contact_icon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Contact_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Contact_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Call_number3 = lv_label_create(ui_Statusbar_group3);
    lv_obj_set_width(ui_Call_number3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Call_number3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Call_number3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Call_number3, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_Call_number3, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Call_number3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Call_number3, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_date3 = lv_label_create(ui_Content_of_objects3);
    lv_obj_set_width(ui_Statusbar_date3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Statusbar_date3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Statusbar_date3, 0);
    lv_obj_set_y(ui_Statusbar_date3, 1);
    lv_obj_set_align(ui_Statusbar_date3, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Statusbar_date3, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_Statusbar_date3, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Statusbar_date3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Statusbar_date3, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Authentication_text = lv_label_create(ui_Content_of_objects3);
    lv_obj_set_width(ui_Authentication_text, lv_pct(46));
    lv_obj_set_height(ui_Authentication_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Authentication_text, 0);
    lv_obj_set_y(ui_Authentication_text, -60);
    lv_obj_set_align(ui_Authentication_text, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Authentication_text,
                      "Please start your EV Charger application and scan this QR code to authenticate your device and set the payment method.");
    lv_obj_set_style_text_color(ui_Authentication_text, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Authentication_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Authentication_text, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg_animcontainer3 = lv_obj_create(ui_Step2);
    lv_obj_set_width(ui_Cardbg_animcontainer3, lv_pct(61));
    lv_obj_set_height(ui_Cardbg_animcontainer3, lv_pct(77));
    lv_obj_clear_flag(ui_Cardbg_animcontainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Cardbg_animcontainer3, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cardbg_animcontainer3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg3 = ui_cardbg_create(ui_Cardbg_animcontainer3);
    lv_obj_set_width(ui_Cardbg3, lv_pct(88));
    lv_obj_set_height(ui_Cardbg3, lv_pct(72));
    lv_obj_set_x(ui_Cardbg3, 0);
    lv_obj_set_y(ui_Cardbg3, 0);
    lv_obj_set_flex_flow(ui_Cardbg3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Cardbg3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(ui_Cardbg3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Cardbg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Step_labels2 = lv_obj_create(ui_Cardbg3);
    lv_obj_remove_style_all(ui_Step_labels2);
    lv_obj_set_width(ui_Step_labels2, lv_pct(100));
    lv_obj_set_height(ui_Step_labels2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Step_labels2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Step_labels2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Step_labels2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Step_labels2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Step_labels2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Step_labels2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Two_icon = lv_label_create(ui_Step_labels2);
    lv_obj_set_width(ui_Two_icon, 50);
    lv_obj_set_height(ui_Two_icon, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_Two_icon, 5);
    lv_obj_set_y(ui_Two_icon, 0);
    lv_label_set_text(ui_Two_icon, "2");
    lv_obj_set_style_text_color(ui_Two_icon, lv_color_hex(0x20203A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Two_icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Two_icon, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Two_icon, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Two_icon, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Two_icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Two_icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Two_icon, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Two_icon, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Two_icon, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Two_icon, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Step3 = lv_label_create(ui_Step_labels2);
    lv_obj_set_width(ui_Step3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Step3, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Step3, 88);
    lv_obj_set_y(ui_Step3, 0);
    lv_label_set_text(ui_Step3, "Step");
    lv_obj_set_style_text_color(ui_Step3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Step3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Step3, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Authentication_h5 = lv_label_create(ui_Cardbg3);
    lv_obj_set_width(ui_Authentication_h5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Authentication_h5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Authentication_h5, 0);
    lv_obj_set_y(ui_Authentication_h5, 99);
    lv_label_set_text(ui_Authentication_h5, "Authentication");
    lv_obj_set_style_text_color(ui_Authentication_h5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Authentication_h5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Authentication_h5, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Phone = lv_img_create(ui_Step2);
    lv_img_set_src(ui_Phone, &ui_img_phone_png);
    lv_obj_set_width(ui_Phone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Phone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Phone, -74);
    lv_obj_set_y(ui_Phone, 40);
    lv_obj_set_align(ui_Phone, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Phone, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Phone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Plagination2 = lv_obj_create(ui_Step2);
    lv_obj_remove_style_all(ui_Plagination2);
    lv_obj_set_height(ui_Plagination2, 30);
    lv_obj_set_width(ui_Plagination2, lv_pct(10));
    lv_obj_set_x(ui_Plagination2, -235);
    lv_obj_set_y(ui_Plagination2, -29);
    lv_obj_set_align(ui_Plagination2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Plagination2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Two_gray_ = lv_label_create(ui_Plagination2);
    lv_obj_set_width(ui_Two_gray_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Two_gray_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Two_gray_, 0);
    lv_obj_set_y(ui_Two_gray_, 5);
    lv_obj_set_align(ui_Two_gray_, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Two_gray_, "/2");
    lv_obj_set_style_text_color(ui_Two_gray_, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Two_gray_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Two_gray_, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Two_black = lv_label_create(ui_Plagination2);
    lv_obj_set_width(ui_Two_black, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Two_black, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Two_black, -40);
    lv_obj_set_y(ui_Two_black, 5);
    lv_obj_set_align(ui_Two_black, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Two_black, "2");
    lv_obj_set_style_text_color(ui_Two_black, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Two_black, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Two_black, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Qr_container = lv_obj_create(ui_Step2);
    lv_obj_remove_style_all(ui_Qr_container);
    lv_obj_set_width(ui_Qr_container, 300);
    lv_obj_set_height(ui_Qr_container, lv_pct(100));
    lv_obj_set_x(ui_Qr_container, 0);
    lv_obj_set_y(ui_Qr_container, -3);
    lv_obj_set_align(ui_Qr_container, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Qr_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Qr_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Qr_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Qr_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Qr_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Qr = lv_img_create(ui_Qr_container);
    lv_img_set_src(ui_Qr, &ui_img_qr_code1_png);
    lv_obj_set_width(ui_Qr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Qr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Qr, -2);
    lv_obj_set_y(ui_Qr, -68);
    lv_obj_set_align(ui_Qr, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Qr, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Qr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Next_button2 = ui_button_create(ui_Step2);
    lv_obj_set_x(ui_Next_button2, -25);
    lv_obj_set_y(ui_Next_button2, -25);
    lv_obj_set_align(ui_Next_button2, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_Next_button2, UI_COMP_BUTTON_BUTTON_LABEL), "Next Step");

    lv_obj_add_event_cb(ui_Pricing_group3, ui_event_Pricing_group3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_help_group3, ui_event_help_group3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Next_button2, ui_event_Next_button2_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Step2, ui_event_Step2, LV_EVENT_ALL, NULL);

}
