// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "ui.h"

void ui_Welcome_screen_init(void)
{
    ui_Welcome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Welcome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Welcome, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Welcome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_bg_img5 = lv_img_create(ui_Welcome);
    lv_img_set_src(ui_Main_bg_img5, &ui_img_bg4_png);
    lv_obj_set_width(ui_Main_bg_img5, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Main_bg_img5, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Main_bg_img5, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Main_bg_img5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Main_bg_img5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Cardbg_animcontainer5 = lv_obj_create(ui_Welcome);
    lv_obj_set_width(ui_Cardbg_animcontainer5, lv_pct(65));
    lv_obj_set_height(ui_Cardbg_animcontainer5, lv_pct(88));
    lv_obj_set_align(ui_Cardbg_animcontainer5, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Cardbg_animcontainer5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Cardbg_animcontainer5, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cardbg_animcontainer5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Cardbg_animcontainer5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg_animcontainer5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg_animcontainer5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg_animcontainer5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cardbg5 = ui_cardbg_create(ui_Cardbg_animcontainer5);
    lv_obj_set_width(ui_Cardbg5, lv_pct(88));
    lv_obj_set_height(ui_Cardbg5, lv_pct(100));
    lv_obj_set_x(ui_Cardbg5, 0);
    lv_obj_set_y(ui_Cardbg5, 0);
    lv_obj_set_flex_flow(ui_Cardbg5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Cardbg5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Cardbg5, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_pad_row(ui_Cardbg5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Cardbg5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Cardbg5, lv_color_hex(0x646473), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cardbg5, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Cardbg5, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Cardbg5, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Cardbg5, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Cardbg5, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Welcome_panel = lv_obj_create(ui_Cardbg5);
    lv_obj_set_width(ui_Welcome_panel, lv_pct(100));
    lv_obj_set_height(ui_Welcome_panel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Welcome_panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Welcome_panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Welcome_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Welcome_panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Welcome_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Welcome_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Welcomimg_title = lv_label_create(ui_Welcome_panel);
    lv_obj_set_width(ui_Welcomimg_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Welcomimg_title, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Welcomimg_title, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Welcomimg_title, "Welcome, Duven");
    lv_obj_set_style_text_color(ui_Welcomimg_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Welcomimg_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Welcomimg_title, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Welcome_text = lv_label_create(ui_Welcome_panel);
    lv_obj_set_width(ui_Welcome_text, lv_pct(100));
    lv_obj_set_height(ui_Welcome_text, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Welcome_text,
                      "The first 30 minutes of fast charging are free. After 60 minutes you get 10% discount.");
    lv_obj_set_style_text_color(ui_Welcome_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Welcome_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Welcome_text, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fee_panel = lv_obj_create(ui_Cardbg5);
    lv_obj_set_width(ui_Fee_panel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Fee_panel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Fee_panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Fee_panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Fee_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Fee_panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Fee_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fee_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fee_label = lv_label_create(ui_Fee_panel);
    lv_obj_set_width(ui_Fee_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fee_label, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Fee_label, "Session fee");
    lv_obj_set_style_text_color(ui_Fee_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Fee_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fee_label, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Price_fee = lv_label_create(ui_Fee_panel);
    lv_obj_set_width(ui_Price_fee, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Price_fee, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Price_fee, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Price_fee, "$0.00");
    lv_obj_set_style_text_color(ui_Price_fee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Price_fee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Price_fee, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_panel = lv_obj_create(ui_Cardbg5);
    lv_obj_set_width(ui_Charging_panel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Charging_panel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Charging_panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Charging_panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Charging_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Charging_panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Charging_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Charging_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_text = lv_label_create(ui_Charging_panel);
    lv_obj_set_width(ui_Charging_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Charging_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Charging_text, 0);
    lv_obj_set_y(ui_Charging_text, 1);
    lv_label_set_text(ui_Charging_text, "1-250 kW charging power will be applied.");
    lv_obj_set_style_text_color(ui_Charging_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Charging_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Charging_text, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Amount_text = lv_label_create(ui_Charging_panel);
    lv_obj_set_width(ui_Amount_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Amount_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Amount_text, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Amount_text, "$0.21/kWh");
    lv_obj_set_style_text_color(ui_Amount_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Amount_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Amount_text, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_speed_panel = lv_obj_create(ui_Cardbg5);
    lv_obj_set_width(ui_Charging_speed_panel, lv_pct(100));
    lv_obj_set_height(ui_Charging_speed_panel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Charging_speed_panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Charging_speed_panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Charging_speed_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Charging_speed_panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Charging_speed_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Charging_speed_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging_speed = lv_label_create(ui_Charging_speed_panel);
    lv_obj_set_width(ui_Charging_speed, lv_pct(100));
    lv_obj_set_height(ui_Charging_speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Charging_speed, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Charging_speed, "The charging speed depends on the type of car\nand the capacity of the network.");
    lv_obj_set_style_text_color(ui_Charging_speed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Charging_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Charging_speed, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Full_content = lv_obj_create(ui_Welcome);
    lv_obj_set_width(ui_Full_content, lv_pct(100));
    lv_obj_set_height(ui_Full_content, lv_pct(100));
    lv_obj_set_align(ui_Full_content, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Full_content, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Full_content, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Full_content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_content, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Content_of_objects5 = lv_obj_create(ui_Full_content);
    lv_obj_set_height(ui_Content_of_objects5, lv_pct(100));
    lv_obj_set_flex_grow(ui_Content_of_objects5, 1);
    lv_obj_set_align(ui_Content_of_objects5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Content_of_objects5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Content_of_objects5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Content_of_objects5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Content_of_objects5, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Content_of_objects5, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Content_of_objects5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Content_of_objects5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_date5 = lv_label_create(ui_Content_of_objects5);
    lv_obj_set_width(ui_Statusbar_date5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Statusbar_date5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Statusbar_date5, 0);
    lv_obj_set_y(ui_Statusbar_date5, 1);
    lv_obj_set_align(ui_Statusbar_date5, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Statusbar_date5, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_Statusbar_date5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Statusbar_date5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Statusbar_date5, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Statusbar_group5 = lv_obj_create(ui_Content_of_objects5);
    lv_obj_set_width(ui_Statusbar_group5, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Statusbar_group5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_Statusbar_group5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Statusbar_group5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Statusbar_group5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Statusbar_group5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Statusbar_group5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Statusbar_group5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Statusbar_group5, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Contact_icon5 = lv_img_create(ui_Statusbar_group5);
    lv_img_set_src(ui_Contact_icon5, &ui_img_contact_png);
    lv_obj_set_width(ui_Contact_icon5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Contact_icon5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Contact_icon5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Contact_icon5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Contact_icon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Contact_icon5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Contact_icon5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Call_number5 = lv_label_create(ui_Statusbar_group5);
    lv_obj_set_width(ui_Call_number5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Call_number5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Call_number5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Call_number5, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_Call_number5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Call_number5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Call_number5, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ready_img_container = lv_obj_create(ui_Welcome);
    lv_obj_remove_style_all(ui_Ready_img_container);
    lv_obj_set_width(ui_Ready_img_container, 250);
    lv_obj_set_height(ui_Ready_img_container, lv_pct(100));
    lv_obj_set_align(ui_Ready_img_container, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Ready_img_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ready = lv_img_create(ui_Ready_img_container);
    lv_img_set_src(ui_ready, &ui_img_ok_png);
    lv_obj_set_width(ui_ready, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ready, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ready, 6);
    lv_obj_set_y(ui_ready, -9);
    lv_obj_set_align(ui_ready, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ready, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_ready, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Continue_button = ui_button_create(ui_Welcome);
    lv_obj_set_x(ui_Continue_button, -18);
    lv_obj_set_y(ui_Continue_button, -26);
    lv_obj_set_align(ui_Continue_button, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_Continue_button, UI_COMP_BUTTON_BUTTON_LABEL), "Continue");

    lv_obj_add_event_cb(ui_Continue_button, ui_event_Continue_button_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Welcome, ui_event_Welcome, LV_EVENT_ALL, NULL);

}
